// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminListContacts = `-- name: AdminListContacts :many
SELECT id, project_id, external_id, phone, email, telegram_chat_id, locale, tags, attributes, created_at, updated_at, name, whatsapp, slack_id, deleted_at FROM contacts
WHERE project_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL
       OR phone ILIKE '%' || $2::text || '%'
       OR email ILIKE '%' || $2::text || '%'
       OR external_id ILIKE '%' || $2::text || '%'
       OR name ILIKE '%' || $2::text || '%')
ORDER BY created_at DESC LIMIT $4 OFFSET $3
`

type AdminListContactsParams struct {
	ProjectID uuid.UUID
	Search    *string
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) AdminListContacts(ctx context.Context, arg AdminListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, adminListContacts,
		arg.ProjectID,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ExternalID,
			&i.Phone,
			&i.Email,
			&i.TelegramChatID,
			&i.Locale,
			&i.Tags,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Whatsapp,
			&i.SlackID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListMessages = `-- name: AdminListMessages :many

SELECT id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version, rendered_subject, rendered_body, status, priority, provider_id, provider_message_id, error_code, error_message, attempts, scheduled_at, sent_at, delivered_at, cost_micros, currency, metadata, idempotency_key, is_test, created_at, updated_at FROM messages
WHERE project_id = $1
  AND ($2::message_status IS NULL OR status = $2::message_status)
  AND ($3::channel IS NULL OR channel = $3::channel)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
  AND ($6::uuid IS NULL OR id < $6::uuid)
  AND ($7::text IS NULL
       OR to_address ILIKE '%' || $7::text || '%'
       OR template_key ILIKE '%' || $7::text || '%'
       OR provider_message_id = $7::text)
  AND ($8::uuid IS NULL OR batch_id = $8::uuid)
  AND ($9::uuid IS NULL OR contact_id = $9::uuid)
  AND ($10::boolean IS NULL OR $10::boolean OR NOT is_test)
ORDER BY id DESC
LIMIT $11
`

type AdminListMessagesParams struct {
	ProjectID   uuid.UUID
	Status      NullMessageStatus
	Channel     NullChannel
	FromTs      *time.Time
	ToTs        *time.Time
	CursorID    *uuid.UUID
	Search      *string
	BatchID     *uuid.UUID
	ContactID   *uuid.UUID
	IncludeTest *bool
	RowLimit    int32
}

// Admin-panel read models: message log, dashboard, usage, health.
func (q *Queries) AdminListMessages(ctx context.Context, arg AdminListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, adminListMessages,
		arg.ProjectID,
		arg.Status,
		arg.Channel,
		arg.FromTs,
		arg.ToTs,
		arg.CursorID,
		arg.Search,
		arg.BatchID,
		arg.ContactID,
		arg.IncludeTest,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BatchID,
			&i.Channel,
			&i.ToAddress,
			&i.ContactID,
			&i.TemplateKey,
			&i.TemplateVersion,
			&i.RenderedSubject,
			&i.RenderedBody,
			&i.Status,
			&i.Priority,
			&i.ProviderID,
			&i.ProviderMessageID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Attempts,
			&i.ScheduledAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.CostMicros,
			&i.Currency,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.IsTest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
WHERE ($1::uuid IS NULL OR project_id = $1::uuid)
`

func (q *Queries) CountAuditLogs(ctx context.Context, projectID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContacts = `-- name: CountContacts :one
SELECT count(*) FROM contacts WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountContacts(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countContacts, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDevices = `-- name: CountDevices :one
SELECT count(*) FILTER (WHERE is_active)::bigint AS active, count(*)::bigint AS total FROM devices WHERE project_id = $1
`

type CountDevicesRow struct {
	Active int64
	Total  int64
}

func (q *Queries) CountDevices(ctx context.Context, projectID uuid.UUID) (CountDevicesRow, error) {
	row := q.db.QueryRow(ctx, countDevices, projectID)
	var i CountDevicesRow
	err := row.Scan(&i.Active, &i.Total)
	return i, err
}

const dashboardDaily = `-- name: DashboardDaily :many
SELECT
    (created_at AT TIME ZONE 'UTC')::date                      AS day,
    channel,
    count(*)::bigint                                           AS total,
    count(*) FILTER (WHERE status = 'sent')::bigint            AS sent,
    count(*) FILTER (WHERE status = 'delivered')::bigint       AS delivered,
    count(*) FILTER (WHERE status = 'failed')::bigint          AS failed,
    count(*) FILTER (WHERE status IN ('queued','processing'))::bigint AS pending,
    coalesce(sum(cost_micros), 0)::bigint                      AS cost_micros
FROM messages
WHERE project_id = $1 AND created_at >= $2 AND created_at < $3 AND NOT is_test
GROUP BY 1, 2
ORDER BY 1, 2
`

type DashboardDailyParams struct {
	ProjectID uuid.UUID
	FromTs    time.Time
	ToTs      time.Time
}

type DashboardDailyRow struct {
	Day        time.Time
	Channel    Channel
	Total      int64
	Sent       int64
	Delivered  int64
	Failed     int64
	Pending    int64
	CostMicros int64
}

// Counts per day per channel in [from, to), by message creation time.
func (q *Queries) DashboardDaily(ctx context.Context, arg DashboardDailyParams) ([]DashboardDailyRow, error) {
	rows, err := q.db.Query(ctx, dashboardDaily, arg.ProjectID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardDailyRow{}
	for rows.Next() {
		var i DashboardDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.Channel,
			&i.Total,
			&i.Sent,
			&i.Delivered,
			&i.Failed,
			&i.Pending,
			&i.CostMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTotals = `-- name: DashboardTotals :one
SELECT
    count(*)::bigint                                                  AS total,
    count(*) FILTER (WHERE status = 'sent')::bigint                   AS sent,
    count(*) FILTER (WHERE status = 'delivered')::bigint              AS delivered,
    count(*) FILTER (WHERE status = 'failed')::bigint                 AS failed,
    count(*) FILTER (WHERE status IN ('queued','processing'))::bigint AS pending,
    coalesce(sum(cost_micros), 0)::bigint                             AS cost_micros
FROM messages
WHERE project_id = $1 AND created_at >= $2 AND created_at < $3 AND NOT is_test
`

type DashboardTotalsParams struct {
	ProjectID uuid.UUID
	FromTs    time.Time
	ToTs      time.Time
}

type DashboardTotalsRow struct {
	Total      int64
	Sent       int64
	Delivered  int64
	Failed     int64
	Pending    int64
	CostMicros int64
}

func (q *Queries) DashboardTotals(ctx context.Context, arg DashboardTotalsParams) (DashboardTotalsRow, error) {
	row := q.db.QueryRow(ctx, dashboardTotals, arg.ProjectID, arg.FromTs, arg.ToTs)
	var i DashboardTotalsRow
	err := row.Scan(
		&i.Total,
		&i.Sent,
		&i.Delivered,
		&i.Failed,
		&i.Pending,
		&i.CostMicros,
	)
	return i, err
}

const deliveryLatency = `-- name: DeliveryLatency :one
SELECT
    coalesce(percentile_cont(0.5)  WITHIN GROUP (ORDER BY extract(epoch FROM (sent_at - created_at))), 0)::float8      AS p50_sent_sec,
    coalesce(percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM (sent_at - created_at))), 0)::float8      AS p95_sent_sec,
    coalesce(percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM (delivered_at - created_at))), 0)::float8 AS p95_delivered_sec,
    count(*) FILTER (WHERE sent_at IS NOT NULL)::bigint AS samples
FROM messages
WHERE project_id = $1 AND created_at >= $2 AND created_at < $3 AND NOT is_test AND sent_at IS NOT NULL
`

type DeliveryLatencyParams struct {
	ProjectID uuid.UUID
	FromTs    time.Time
	ToTs      time.Time
}

type DeliveryLatencyRow struct {
	P50SentSec      float64
	P95SentSec      float64
	P95DeliveredSec float64
	Samples         int64
}

// Seconds from creation to sent / delivered; percentiles over the window.
func (q *Queries) DeliveryLatency(ctx context.Context, arg DeliveryLatencyParams) (DeliveryLatencyRow, error) {
	row := q.db.QueryRow(ctx, deliveryLatency, arg.ProjectID, arg.FromTs, arg.ToTs)
	var i DeliveryLatencyRow
	err := row.Scan(
		&i.P50SentSec,
		&i.P95SentSec,
		&i.P95DeliveredSec,
		&i.Samples,
	)
	return i, err
}

const globalCounts = `-- name: GlobalCounts :one
SELECT
    (SELECT count(*) FROM projects)::bigint                                              AS projects,
    (SELECT count(*) FROM users WHERE is_active)::bigint                                 AS users,
    (SELECT count(*) FROM messages WHERE created_at >= now() - interval '24 hours')::bigint AS messages_24h,
    (SELECT count(*) FROM messages WHERE status IN ('queued','processing'))::bigint      AS pending,
    (SELECT count(*) FROM webhook_deliveries WHERE delivered_at IS NULL AND next_retry_at IS NOT NULL)::bigint AS webhooks_pending
`

type GlobalCountsRow struct {
	Projects        int64
	Users           int64
	Messages24h     int64
	Pending         int64
	WebhooksPending int64
}

func (q *Queries) GlobalCounts(ctx context.Context) (GlobalCountsRow, error) {
	row := q.db.QueryRow(ctx, globalCounts)
	var i GlobalCountsRow
	err := row.Scan(
		&i.Projects,
		&i.Users,
		&i.Messages24h,
		&i.Pending,
		&i.WebhooksPending,
	)
	return i, err
}

const listWebhookDeliveriesFiltered = `-- name: ListWebhookDeliveriesFiltered :many
SELECT id, project_id, message_id, batch_id, event, url, payload, signature, response_code, response_body, attempts, next_retry_at, delivered_at, created_at FROM webhook_deliveries
WHERE project_id = $1
  AND ($2::text IS NULL OR event = $2::text)
  AND ($3::boolean IS NULL OR NOT $3::boolean OR delivered_at IS NULL)
  AND ($4::uuid IS NULL OR message_id = $4::uuid)
ORDER BY created_at DESC LIMIT $6 OFFSET $5
`

type ListWebhookDeliveriesFilteredParams struct {
	ProjectID  uuid.UUID
	Event      *string
	OnlyFailed *bool
	MessageID  *uuid.UUID
	RowOffset  int32
	RowLimit   int32
}

func (q *Queries) ListWebhookDeliveriesFiltered(ctx context.Context, arg ListWebhookDeliveriesFilteredParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesFiltered,
		arg.ProjectID,
		arg.Event,
		arg.OnlyFailed,
		arg.MessageID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MessageID,
			&i.BatchID,
			&i.Event,
			&i.Url,
			&i.Payload,
			&i.Signature,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.Attempts,
			&i.NextRetryAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const providerStats = `-- name: ProviderStats :many
SELECT
    p.id, p.name, p.channel, p.type, p.is_active, p.priority,
    count(m.id) FILTER (WHERE m.status IN ('sent','delivered'))::bigint AS ok_count,
    count(m.id) FILTER (WHERE m.status = 'failed')::bigint              AS failed_count,
    coalesce(max(m.sent_at), '0001-01-01 00:00:00+00'::timestamptz)::timestamptz AS last_sent_at
FROM providers p
LEFT JOIN messages m ON m.provider_id = p.id AND m.created_at >= $1
WHERE p.project_id = $2
GROUP BY p.id
ORDER BY p.channel, p.priority
`

type ProviderStatsParams struct {
	FromTs    time.Time
	ProjectID uuid.UUID
}

type ProviderStatsRow struct {
	ID          uuid.UUID
	Name        string
	Channel     Channel
	Type        ProviderType
	IsActive    bool
	Priority    int32
	OkCount     int64
	FailedCount int64
	LastSentAt  time.Time
}

// Per-provider outcome counts in the window (for the health page).
func (q *Queries) ProviderStats(ctx context.Context, arg ProviderStatsParams) ([]ProviderStatsRow, error) {
	rows, err := q.db.Query(ctx, providerStats, arg.FromTs, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderStatsRow{}
	for rows.Next() {
		var i ProviderStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Channel,
			&i.Type,
			&i.IsActive,
			&i.Priority,
			&i.OkCount,
			&i.FailedCount,
			&i.LastSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentFailures = `-- name: RecentFailures :many
SELECT id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version, rendered_subject, rendered_body, status, priority, provider_id, provider_message_id, error_code, error_message, attempts, scheduled_at, sent_at, delivered_at, cost_micros, currency, metadata, idempotency_key, is_test, created_at, updated_at FROM messages
WHERE project_id = $1 AND status = 'failed' AND created_at >= $2 AND NOT is_test
ORDER BY id DESC LIMIT $3
`

type RecentFailuresParams struct {
	ProjectID uuid.UUID
	FromTs    time.Time
	RowLimit  int32
}

func (q *Queries) RecentFailures(ctx context.Context, arg RecentFailuresParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, recentFailures, arg.ProjectID, arg.FromTs, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BatchID,
			&i.Channel,
			&i.ToAddress,
			&i.ContactID,
			&i.TemplateKey,
			&i.TemplateVersion,
			&i.RenderedSubject,
			&i.RenderedBody,
			&i.Status,
			&i.Priority,
			&i.ProviderID,
			&i.ProviderMessageID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Attempts,
			&i.ScheduledAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.CostMicros,
			&i.Currency,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.IsTest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
