// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_keys.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (project_id, name, prefix, hint, key_hash, scopes, ip_allowlist, expires_at, require_signature)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, name, prefix, hint, key_hash, scopes, ip_allowlist, last_used_at, expires_at, revoked_at, created_at, require_signature
`

type CreateAPIKeyParams struct {
	ProjectID        uuid.UUID
	Name             string
	Prefix           string
	Hint             string
	KeyHash          []byte
	Scopes           []string
	IpAllowlist      []string
	ExpiresAt        *time.Time
	RequireSignature bool
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ProjectID,
		arg.Name,
		arg.Prefix,
		arg.Hint,
		arg.KeyHash,
		arg.Scopes,
		arg.IpAllowlist,
		arg.ExpiresAt,
		arg.RequireSignature,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.Hint,
		&i.KeyHash,
		&i.Scopes,
		&i.IpAllowlist,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RequireSignature,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, project_id, name, prefix, hint, key_hash, scopes, ip_allowlist, last_used_at, expires_at, revoked_at, created_at, require_signature FROM api_keys WHERE id = $1 AND project_id = $2
`

type GetAPIKeyParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.ID, arg.ProjectID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.Hint,
		&i.KeyHash,
		&i.Scopes,
		&i.IpAllowlist,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RequireSignature,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, project_id, name, prefix, hint, key_hash, scopes, ip_allowlist, last_used_at, expires_at, revoked_at, created_at, require_signature FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.Hint,
		&i.KeyHash,
		&i.Scopes,
		&i.IpAllowlist,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RequireSignature,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, project_id, name, prefix, hint, key_hash, scopes, ip_allowlist, last_used_at, expires_at, revoked_at, created_at, require_signature FROM api_keys WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, projectID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Prefix,
			&i.Hint,
			&i.KeyHash,
			&i.Scopes,
			&i.IpAllowlist,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.RequireSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND project_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_keys SET
    name              = $1,
    scopes            = $2,
    ip_allowlist      = $3,
    require_signature = $4
WHERE id = $5 AND project_id = $6 AND revoked_at IS NULL
RETURNING id, project_id, name, prefix, hint, key_hash, scopes, ip_allowlist, last_used_at, expires_at, revoked_at, created_at, require_signature
`

type UpdateAPIKeyParams struct {
	Name             string
	Scopes           []string
	IpAllowlist      []string
	RequireSignature bool
	ID               uuid.UUID
	ProjectID        uuid.UUID
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKey,
		arg.Name,
		arg.Scopes,
		arg.IpAllowlist,
		arg.RequireSignature,
		arg.ID,
		arg.ProjectID,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.Hint,
		&i.KeyHash,
		&i.Scopes,
		&i.IpAllowlist,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RequireSignature,
	)
	return i, err
}
