// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: attachments.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (id, uploaded_by, content_type, size_bytes, filename, data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uploaded_by, content_type, size_bytes, filename, created_at
`

type CreateAttachmentParams struct {
	ID          uuid.UUID
	UploadedBy  *uuid.UUID
	ContentType string
	SizeBytes   int32
	Filename    string
	Data        []byte
}

type CreateAttachmentRow struct {
	ID          uuid.UUID
	UploadedBy  *uuid.UUID
	ContentType string
	SizeBytes   int32
	Filename    string
	CreatedAt   time.Time
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.UploadedBy,
		arg.ContentType,
		arg.SizeBytes,
		arg.Filename,
		arg.Data,
	)
	var i CreateAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.UploadedBy,
		&i.ContentType,
		&i.SizeBytes,
		&i.Filename,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, uploaded_by, content_type, size_bytes, filename, data, created_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UploadedBy,
		&i.ContentType,
		&i.SizeBytes,
		&i.Filename,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}
