// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addChatMember = `-- name: AddChatMember :exec
INSERT INTO chat_members (channel_id, user_id, role, last_read_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (channel_id, user_id) DO NOTHING
`

type AddChatMemberParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
	Role      string
}

func (q *Queries) AddChatMember(ctx context.Context, arg AddChatMemberParams) error {
	_, err := q.db.Exec(ctx, addChatMember, arg.ChannelID, arg.UserID, arg.Role)
	return err
}

const autoJoinPublicChannels = `-- name: AutoJoinPublicChannels :exec
INSERT INTO chat_members (channel_id, user_id)
SELECT c.id, $1 FROM chat_channels c WHERE c.kind = 'public'
ON CONFLICT (channel_id, user_id) DO NOTHING
`

func (q *Queries) AutoJoinPublicChannels(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, autoJoinPublicChannels, userID)
	return err
}

const channelLastMessages = `-- name: ChannelLastMessages :many
SELECT DISTINCT ON (m.channel_id)
  m.channel_id, m.body, m.created_at, m.user_id, (m.attachment_id IS NOT NULL)::boolean AS has_attachment
FROM chat_messages m
JOIN chat_members mem ON mem.channel_id = m.channel_id AND mem.user_id = $1
WHERE m.deleted_at IS NULL
ORDER BY m.channel_id, m.id DESC
`

type ChannelLastMessagesRow struct {
	ChannelID     uuid.UUID
	Body          string
	CreatedAt     time.Time
	UserID        *uuid.UUID
	HasAttachment bool
}

func (q *Queries) ChannelLastMessages(ctx context.Context, userID uuid.UUID) ([]ChannelLastMessagesRow, error) {
	rows, err := q.db.Query(ctx, channelLastMessages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelLastMessagesRow{}
	for rows.Next() {
		var i ChannelLastMessagesRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Body,
			&i.CreatedAt,
			&i.UserID,
			&i.HasAttachment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelUnreadCounts = `-- name: ChannelUnreadCounts :many
SELECT mem.channel_id, count(m.id)::bigint AS unread
FROM chat_members mem
LEFT JOIN chat_messages m ON m.channel_id = mem.channel_id AND m.deleted_at IS NULL
  AND m.created_at > mem.last_read_at AND (m.user_id IS NULL OR m.user_id <> mem.user_id)
WHERE mem.user_id = $1
GROUP BY mem.channel_id
`

type ChannelUnreadCountsRow struct {
	ChannelID uuid.UUID
	Unread    int64
}

func (q *Queries) ChannelUnreadCounts(ctx context.Context, userID uuid.UUID) ([]ChannelUnreadCountsRow, error) {
	rows, err := q.db.Query(ctx, channelUnreadCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelUnreadCountsRow{}
	for rows.Next() {
		var i ChannelUnreadCountsRow
		if err := rows.Scan(&i.ChannelID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO chat_channels (id, kind, name, topic, created_by, dm_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, kind, name, topic, created_by, dm_key, created_at, updated_at
`

type CreateChannelParams struct {
	ID        uuid.UUID
	Kind      ChatChannelKind
	Name      string
	Topic     string
	CreatedBy *uuid.UUID
	DmKey     *string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Topic,
		arg.CreatedBy,
		arg.DmKey,
	)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.CreatedBy,
		&i.DmKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (id, channel_id, user_id, body, attachment_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, channel_id, user_id, body, attachment_id, created_at, edited_at, deleted_at
`

type CreateChatMessageParams struct {
	ID           uuid.UUID
	ChannelID    uuid.UUID
	UserID       *uuid.UUID
	Body         string
	AttachmentID *uuid.UUID
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ID,
		arg.ChannelID,
		arg.UserID,
		arg.Body,
		arg.AttachmentID,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Body,
		&i.AttachmentID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const directPeers = `-- name: DirectPeers :many
SELECT m2.channel_id, u.id AS user_id, u.full_name, u.avatar_id
FROM chat_members m2
JOIN chat_channels c ON c.id = m2.channel_id AND c.kind = 'direct'
JOIN users u ON u.id = m2.user_id
JOIN chat_members me ON me.channel_id = m2.channel_id AND me.user_id = $1
WHERE m2.user_id <> $1
`

type DirectPeersRow struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
	FullName  string
	AvatarID  *uuid.UUID
}

func (q *Queries) DirectPeers(ctx context.Context, userID uuid.UUID) ([]DirectPeersRow, error) {
	rows, err := q.db.Query(ctx, directPeers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectPeersRow{}
	for rows.Next() {
		var i DirectPeersRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.FullName,
			&i.AvatarID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, kind, name, topic, created_by, dm_key, created_at, updated_at FROM chat_channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.CreatedBy,
		&i.DmKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatMember = `-- name: GetChatMember :one
SELECT channel_id, user_id, role, last_read_at, joined_at FROM chat_members WHERE channel_id = $1 AND user_id = $2
`

type GetChatMemberParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetChatMember(ctx context.Context, arg GetChatMemberParams) (ChatMember, error) {
	row := q.db.QueryRow(ctx, getChatMember, arg.ChannelID, arg.UserID)
	var i ChatMember
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Role,
		&i.LastReadAt,
		&i.JoinedAt,
	)
	return i, err
}

const getChatMessage = `-- name: GetChatMessage :one
SELECT id, channel_id, user_id, body, attachment_id, created_at, edited_at, deleted_at FROM chat_messages WHERE id = $1 AND channel_id = $2
`

type GetChatMessageParams struct {
	ID        uuid.UUID
	ChannelID uuid.UUID
}

func (q *Queries) GetChatMessage(ctx context.Context, arg GetChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessage, arg.ID, arg.ChannelID)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Body,
		&i.AttachmentID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDirectChannel = `-- name: GetDirectChannel :one
SELECT id, kind, name, topic, created_by, dm_key, created_at, updated_at FROM chat_channels WHERE dm_key = $1
`

func (q *Queries) GetDirectChannel(ctx context.Context, dmKey *string) (ChatChannel, error) {
	row := q.db.QueryRow(ctx, getDirectChannel, dmKey)
	var i ChatChannel
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.CreatedBy,
		&i.DmKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelMembers = `-- name: ListChannelMembers :many
SELECT u.id, u.full_name, u.email, u.avatar_id, u.bio, m.role, m.joined_at
FROM chat_members m JOIN users u ON u.id = m.user_id
WHERE m.channel_id = $1
ORDER BY u.full_name
`

type ListChannelMembersRow struct {
	ID       uuid.UUID
	FullName string
	Email    string
	AvatarID *uuid.UUID
	Bio      string
	Role     string
	JoinedAt time.Time
}

func (q *Queries) ListChannelMembers(ctx context.Context, channelID uuid.UUID) ([]ListChannelMembersRow, error) {
	rows, err := q.db.Query(ctx, listChannelMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelMembersRow{}
	for rows.Next() {
		var i ListChannelMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.AvatarID,
			&i.Bio,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT m.id, m.channel_id, m.user_id, m.body, m.attachment_id, m.created_at, m.edited_at,
  u.full_name AS author_name, u.avatar_id AS author_avatar,
  a.content_type AS attachment_type, a.filename AS attachment_name, a.size_bytes AS attachment_size
FROM chat_messages m
LEFT JOIN users u ON u.id = m.user_id
LEFT JOIN attachments a ON a.id = m.attachment_id
WHERE m.channel_id = $1 AND m.deleted_at IS NULL
  AND ($2::uuid IS NULL OR m.id < $2::uuid)
ORDER BY m.id DESC
LIMIT $3
`

type ListChatMessagesParams struct {
	ChannelID uuid.UUID
	Before    *uuid.UUID
	RowLimit  int32
}

type ListChatMessagesRow struct {
	ID             uuid.UUID
	ChannelID      uuid.UUID
	UserID         *uuid.UUID
	Body           string
	AttachmentID   *uuid.UUID
	CreatedAt      time.Time
	EditedAt       *time.Time
	AuthorName     *string
	AuthorAvatar   *uuid.UUID
	AttachmentType *string
	AttachmentName *string
	AttachmentSize *int32
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ListChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChatMessages, arg.ChannelID, arg.Before, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatMessagesRow{}
	for rows.Next() {
		var i ListChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Body,
			&i.AttachmentID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AttachmentType,
			&i.AttachmentName,
			&i.AttachmentSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyChannelRows = `-- name: ListMyChannelRows :many
SELECT c.id, c.kind, c.name, c.topic, c.created_by, c.dm_key, c.created_at, c.updated_at, mem.last_read_at FROM chat_members mem
JOIN chat_channels c ON c.id = mem.channel_id
WHERE mem.user_id = $1
`

type ListMyChannelRowsRow struct {
	ID         uuid.UUID
	Kind       ChatChannelKind
	Name       string
	Topic      string
	CreatedBy  *uuid.UUID
	DmKey      *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastReadAt time.Time
}

func (q *Queries) ListMyChannelRows(ctx context.Context, userID uuid.UUID) ([]ListMyChannelRowsRow, error) {
	rows, err := q.db.Query(ctx, listMyChannelRows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyChannelRowsRow{}
	for rows.Next() {
		var i ListMyChannelRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.CreatedBy,
			&i.DmKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelRead = `-- name: MarkChannelRead :exec
UPDATE chat_members SET last_read_at = now() WHERE channel_id = $1 AND user_id = $2
`

type MarkChannelReadParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) MarkChannelRead(ctx context.Context, arg MarkChannelReadParams) error {
	_, err := q.db.Exec(ctx, markChannelRead, arg.ChannelID, arg.UserID)
	return err
}

const removeChatMember = `-- name: RemoveChatMember :execrows
DELETE FROM chat_members WHERE channel_id = $1 AND user_id = $2
`

type RemoveChatMemberParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveChatMember(ctx context.Context, arg RemoveChatMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeChatMember, arg.ChannelID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteChatMessage = `-- name: SoftDeleteChatMessage :execrows
UPDATE chat_messages SET deleted_at = now() WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteChatMessageParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
}

func (q *Queries) SoftDeleteChatMessage(ctx context.Context, arg SoftDeleteChatMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteChatMessage, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchChannel = `-- name: TouchChannel :exec
UPDATE chat_channels SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchChannel, id)
	return err
}
