// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contacts.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (project_id, external_id, phone, email, telegram_chat_id, locale, tags, attributes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, external_id, phone, email, telegram_chat_id, locale, tags, attributes, created_at, updated_at
`

type CreateContactParams struct {
	ProjectID      uuid.UUID
	ExternalID     string
	Phone          string
	Email          string
	TelegramChatID string
	Locale         string
	Tags           []string
	Attributes     json.RawMessage
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.ProjectID,
		arg.ExternalID,
		arg.Phone,
		arg.Email,
		arg.TelegramChatID,
		arg.Locale,
		arg.Tags,
		arg.Attributes,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalID,
		&i.Phone,
		&i.Email,
		&i.TelegramChatID,
		&i.Locale,
		&i.Tags,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM contacts WHERE id = $1 AND project_id = $2
`

type DeleteContactParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContact, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeviceByToken = `-- name: DeleteDeviceByToken :execrows
DELETE FROM devices WHERE fcm_token = $1 AND project_id = $2
`

type DeleteDeviceByTokenParams struct {
	FcmToken  string
	ProjectID uuid.UUID
}

func (q *Queries) DeleteDeviceByToken(ctx context.Context, arg DeleteDeviceByTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeviceByToken, arg.FcmToken, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableDeviceByToken = `-- name: DisableDeviceByToken :execrows
UPDATE devices SET is_active = false WHERE fcm_token = $1 AND is_active
`

func (q *Queries) DisableDeviceByToken(ctx context.Context, fcmToken string) (int64, error) {
	result, err := q.db.Exec(ctx, disableDeviceByToken, fcmToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContact = `-- name: GetContact :one
SELECT id, project_id, external_id, phone, email, telegram_chat_id, locale, tags, attributes, created_at, updated_at FROM contacts WHERE id = $1 AND project_id = $2
`

type GetContactParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, arg.ID, arg.ProjectID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalID,
		&i.Phone,
		&i.Email,
		&i.TelegramChatID,
		&i.Locale,
		&i.Tags,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactByEmail = `-- name: GetContactByEmail :one
SELECT id, project_id, external_id, phone, email, telegram_chat_id, locale, tags, attributes, created_at, updated_at FROM contacts WHERE project_id = $1 AND email = lower($2) LIMIT 1
`

type GetContactByEmailParams struct {
	ProjectID uuid.UUID
	Email     string
}

func (q *Queries) GetContactByEmail(ctx context.Context, arg GetContactByEmailParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByEmail, arg.ProjectID, arg.Email)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalID,
		&i.Phone,
		&i.Email,
		&i.TelegramChatID,
		&i.Locale,
		&i.Tags,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactByExternalID = `-- name: GetContactByExternalID :one
SELECT id, project_id, external_id, phone, email, telegram_chat_id, locale, tags, attributes, created_at, updated_at FROM contacts WHERE project_id = $1 AND external_id = $2
`

type GetContactByExternalIDParams struct {
	ProjectID  uuid.UUID
	ExternalID string
}

func (q *Queries) GetContactByExternalID(ctx context.Context, arg GetContactByExternalIDParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByExternalID, arg.ProjectID, arg.ExternalID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalID,
		&i.Phone,
		&i.Email,
		&i.TelegramChatID,
		&i.Locale,
		&i.Tags,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactByPhone = `-- name: GetContactByPhone :one
SELECT id, project_id, external_id, phone, email, telegram_chat_id, locale, tags, attributes, created_at, updated_at FROM contacts WHERE project_id = $1 AND phone = $2 LIMIT 1
`

type GetContactByPhoneParams struct {
	ProjectID uuid.UUID
	Phone     string
}

func (q *Queries) GetContactByPhone(ctx context.Context, arg GetContactByPhoneParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByPhone, arg.ProjectID, arg.Phone)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalID,
		&i.Phone,
		&i.Email,
		&i.TelegramChatID,
		&i.Locale,
		&i.Tags,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByToken = `-- name: GetDeviceByToken :one
SELECT id, project_id, contact_id, platform, fcm_token, app_version, last_seen_at, is_active, created_at FROM devices WHERE fcm_token = $1
`

func (q *Queries) GetDeviceByToken(ctx context.Context, fcmToken string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByToken, fcmToken)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ContactID,
		&i.Platform,
		&i.FcmToken,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveDevicesForContact = `-- name: ListActiveDevicesForContact :many
SELECT id, project_id, contact_id, platform, fcm_token, app_version, last_seen_at, is_active, created_at FROM devices WHERE contact_id = $1 AND is_active ORDER BY last_seen_at DESC
`

func (q *Queries) ListActiveDevicesForContact(ctx context.Context, contactID *uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listActiveDevicesForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ContactID,
			&i.Platform,
			&i.FcmToken,
			&i.AppVersion,
			&i.LastSeenAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT id, project_id, external_id, phone, email, telegram_chat_id, locale, tags, attributes, created_at, updated_at FROM contacts
WHERE project_id = $1
  AND ($2::text IS NULL OR $2::text = ANY (tags))
  AND ($3::text IS NULL
       OR phone ILIKE '%' || $3::text || '%'
       OR email ILIKE '%' || $3::text || '%'
       OR external_id ILIKE '%' || $3::text || '%')
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListContactsParams struct {
	ProjectID uuid.UUID
	Tag       *string
	Search    *string
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.ProjectID,
		arg.Tag,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ExternalID,
			&i.Phone,
			&i.Email,
			&i.TelegramChatID,
			&i.Locale,
			&i.Tags,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT id, project_id, contact_id, platform, fcm_token, app_version, last_seen_at, is_active, created_at FROM devices WHERE project_id = $1 ORDER BY last_seen_at DESC LIMIT $3 OFFSET $2
`

type ListDevicesParams struct {
	ProjectID uuid.UUID
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices, arg.ProjectID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ContactID,
			&i.Platform,
			&i.FcmToken,
			&i.AppVersion,
			&i.LastSeenAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts SET
    external_id      = $1,
    phone            = $2,
    email            = $3,
    telegram_chat_id = $4,
    locale           = $5,
    tags             = $6,
    attributes       = $7,
    updated_at       = now()
WHERE id = $8 AND project_id = $9
RETURNING id, project_id, external_id, phone, email, telegram_chat_id, locale, tags, attributes, created_at, updated_at
`

type UpdateContactParams struct {
	ExternalID     string
	Phone          string
	Email          string
	TelegramChatID string
	Locale         string
	Tags           []string
	Attributes     json.RawMessage
	ID             uuid.UUID
	ProjectID      uuid.UUID
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.ExternalID,
		arg.Phone,
		arg.Email,
		arg.TelegramChatID,
		arg.Locale,
		arg.Tags,
		arg.Attributes,
		arg.ID,
		arg.ProjectID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalID,
		&i.Phone,
		&i.Email,
		&i.TelegramChatID,
		&i.Locale,
		&i.Tags,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (project_id, contact_id, platform, fcm_token, app_version, last_seen_at, is_active)
VALUES ($1, $2, $3, $4, $5, now(), true)
ON CONFLICT (fcm_token) DO UPDATE SET
    project_id   = EXCLUDED.project_id,
    contact_id   = COALESCE(EXCLUDED.contact_id, devices.contact_id),
    platform     = EXCLUDED.platform,
    app_version  = EXCLUDED.app_version,
    last_seen_at = now(),
    is_active    = true
RETURNING id, project_id, contact_id, platform, fcm_token, app_version, last_seen_at, is_active, created_at
`

type UpsertDeviceParams struct {
	ProjectID  uuid.UUID
	ContactID  *uuid.UUID
	Platform   DevicePlatform
	FcmToken   string
	AppVersion string
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ProjectID,
		arg.ContactID,
		arg.Platform,
		arg.FcmToken,
		arg.AppVersion,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ContactID,
		&i.Platform,
		&i.FcmToken,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
