// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gateway.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countGatewayInbound = `-- name: CountGatewayInbound :one
SELECT count(*)::bigint FROM gateway_inbound WHERE project_id = $1
`

func (q *Queries) CountGatewayInbound(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGatewayInbound, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countGatewayOutboxPending = `-- name: CountGatewayOutboxPending :one
SELECT count(*)::bigint FROM gateway_outbox
WHERE provider_id = $1 AND status IN ('pending', 'leased') AND expires_at > now()
`

func (q *Queries) CountGatewayOutboxPending(ctx context.Context, providerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGatewayOutboxPending, providerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const enqueueGatewayOutbox = `-- name: EnqueueGatewayOutbox :one
INSERT INTO gateway_outbox (id, provider_id, message_id, to_address, text, sim_slot, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider_id, message_id, to_address, text, sim_slot, status, error_code, error_message, parts, expires_at, leased_at, sent_at, delivered_at, created_at, updated_at
`

type EnqueueGatewayOutboxParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
	MessageID  uuid.UUID
	ToAddress  string
	Text       string
	SimSlot    int32
	ExpiresAt  time.Time
}

func (q *Queries) EnqueueGatewayOutbox(ctx context.Context, arg EnqueueGatewayOutboxParams) (GatewayOutbox, error) {
	row := q.db.QueryRow(ctx, enqueueGatewayOutbox,
		arg.ID,
		arg.ProviderID,
		arg.MessageID,
		arg.ToAddress,
		arg.Text,
		arg.SimSlot,
		arg.ExpiresAt,
	)
	var i GatewayOutbox
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.MessageID,
		&i.ToAddress,
		&i.Text,
		&i.SimSlot,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Parts,
		&i.ExpiresAt,
		&i.LeasedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireGatewayOutbox = `-- name: ExpireGatewayOutbox :execrows
UPDATE gateway_outbox SET status = 'expired', updated_at = now()
WHERE id = $1 AND status IN ('pending', 'leased')
`

func (q *Queries) ExpireGatewayOutbox(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, expireGatewayOutbox, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGatewayDevice = `-- name: GetGatewayDevice :one
SELECT provider_id, project_id, key_hash, last_seen_at, device_info, created_at, updated_at FROM gateway_devices WHERE provider_id = $1
`

func (q *Queries) GetGatewayDevice(ctx context.Context, providerID uuid.UUID) (GatewayDevice, error) {
	row := q.db.QueryRow(ctx, getGatewayDevice, providerID)
	var i GatewayDevice
	err := row.Scan(
		&i.ProviderID,
		&i.ProjectID,
		&i.KeyHash,
		&i.LastSeenAt,
		&i.DeviceInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGatewayDeviceByKeyHash = `-- name: GetGatewayDeviceByKeyHash :one
SELECT provider_id, project_id, key_hash, last_seen_at, device_info, created_at, updated_at FROM gateway_devices WHERE key_hash = $1
`

func (q *Queries) GetGatewayDeviceByKeyHash(ctx context.Context, keyHash []byte) (GatewayDevice, error) {
	row := q.db.QueryRow(ctx, getGatewayDeviceByKeyHash, keyHash)
	var i GatewayDevice
	err := row.Scan(
		&i.ProviderID,
		&i.ProjectID,
		&i.KeyHash,
		&i.LastSeenAt,
		&i.DeviceInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGatewayOutbox = `-- name: GetGatewayOutbox :one
SELECT id, provider_id, message_id, to_address, text, sim_slot, status, error_code, error_message, parts, expires_at, leased_at, sent_at, delivered_at, created_at, updated_at FROM gateway_outbox WHERE id = $1
`

func (q *Queries) GetGatewayOutbox(ctx context.Context, id uuid.UUID) (GatewayOutbox, error) {
	row := q.db.QueryRow(ctx, getGatewayOutbox, id)
	var i GatewayOutbox
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.MessageID,
		&i.ToAddress,
		&i.Text,
		&i.SimSlot,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Parts,
		&i.ExpiresAt,
		&i.LeasedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGatewayOutboxForProvider = `-- name: GetGatewayOutboxForProvider :one
SELECT id, provider_id, message_id, to_address, text, sim_slot, status, error_code, error_message, parts, expires_at, leased_at, sent_at, delivered_at, created_at, updated_at FROM gateway_outbox WHERE id = $1 AND provider_id = $2
`

type GetGatewayOutboxForProviderParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) GetGatewayOutboxForProvider(ctx context.Context, arg GetGatewayOutboxForProviderParams) (GatewayOutbox, error) {
	row := q.db.QueryRow(ctx, getGatewayOutboxForProvider, arg.ID, arg.ProviderID)
	var i GatewayOutbox
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.MessageID,
		&i.ToAddress,
		&i.Text,
		&i.SimSlot,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Parts,
		&i.ExpiresAt,
		&i.LeasedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGatewayInbound = `-- name: InsertGatewayInbound :one
INSERT INTO gateway_inbound (id, provider_id, project_id, from_address, text, received_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider_id, project_id, from_address, text, received_at, created_at
`

type InsertGatewayInboundParams struct {
	ID          uuid.UUID
	ProviderID  uuid.UUID
	ProjectID   uuid.UUID
	FromAddress string
	Text        string
	ReceivedAt  time.Time
}

func (q *Queries) InsertGatewayInbound(ctx context.Context, arg InsertGatewayInboundParams) (GatewayInbound, error) {
	row := q.db.QueryRow(ctx, insertGatewayInbound,
		arg.ID,
		arg.ProviderID,
		arg.ProjectID,
		arg.FromAddress,
		arg.Text,
		arg.ReceivedAt,
	)
	var i GatewayInbound
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProjectID,
		&i.FromAddress,
		&i.Text,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const leaseGatewayOutbox = `-- name: LeaseGatewayOutbox :many
UPDATE gateway_outbox o SET status = 'leased', leased_at = now(), updated_at = now()
WHERE o.id IN (
    SELECT g.id FROM gateway_outbox g
    WHERE g.provider_id = $1 AND g.status = 'pending' AND g.expires_at > now()
    ORDER BY g.created_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING o.id, o.provider_id, o.message_id, o.to_address, o.text, o.sim_slot, o.status, o.error_code, o.error_message, o.parts, o.expires_at, o.leased_at, o.sent_at, o.delivered_at, o.created_at, o.updated_at
`

type LeaseGatewayOutboxParams struct {
	ProviderID uuid.UUID
	RowLimit   int32
}

func (q *Queries) LeaseGatewayOutbox(ctx context.Context, arg LeaseGatewayOutboxParams) ([]GatewayOutbox, error) {
	rows, err := q.db.Query(ctx, leaseGatewayOutbox, arg.ProviderID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayOutbox{}
	for rows.Next() {
		var i GatewayOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.MessageID,
			&i.ToAddress,
			&i.Text,
			&i.SimSlot,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Parts,
			&i.ExpiresAt,
			&i.LeasedAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayDevicesForProject = `-- name: ListGatewayDevicesForProject :many
SELECT provider_id, project_id, key_hash, last_seen_at, device_info, created_at, updated_at FROM gateway_devices WHERE project_id = $1
`

func (q *Queries) ListGatewayDevicesForProject(ctx context.Context, projectID uuid.UUID) ([]GatewayDevice, error) {
	rows, err := q.db.Query(ctx, listGatewayDevicesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayDevice{}
	for rows.Next() {
		var i GatewayDevice
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProjectID,
			&i.KeyHash,
			&i.LastSeenAt,
			&i.DeviceInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayInbound = `-- name: ListGatewayInbound :many
SELECT id, provider_id, project_id, from_address, text, received_at, created_at FROM gateway_inbound WHERE project_id = $1
ORDER BY received_at DESC LIMIT $3 OFFSET $2
`

type ListGatewayInboundParams struct {
	ProjectID uuid.UUID
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListGatewayInbound(ctx context.Context, arg ListGatewayInboundParams) ([]GatewayInbound, error) {
	rows, err := q.db.Query(ctx, listGatewayInbound, arg.ProjectID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayInbound{}
	for rows.Next() {
		var i GatewayInbound
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ProjectID,
			&i.FromAddress,
			&i.Text,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeGatewayOutbox = `-- name: PurgeGatewayOutbox :execrows
DELETE FROM gateway_outbox WHERE created_at < $1
`

func (q *Queries) PurgeGatewayOutbox(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeGatewayOutbox, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGatewayOutboxResult = `-- name: SetGatewayOutboxResult :one
UPDATE gateway_outbox SET
    status        = $1,
    error_code    = $2,
    error_message = $3,
    parts         = CASE WHEN $4::int > 0 THEN $4::int ELSE parts END,
    sent_at       = CASE WHEN $1::text IN ('sent', 'delivered') AND sent_at IS NULL THEN now() ELSE sent_at END,
    delivered_at  = CASE WHEN $1::text = 'delivered' THEN now() ELSE delivered_at END,
    updated_at    = now()
WHERE id = $5
RETURNING id, provider_id, message_id, to_address, text, sim_slot, status, error_code, error_message, parts, expires_at, leased_at, sent_at, delivered_at, created_at, updated_at
`

type SetGatewayOutboxResultParams struct {
	Status       string
	ErrorCode    string
	ErrorMessage string
	Parts        int32
	ID           uuid.UUID
}

func (q *Queries) SetGatewayOutboxResult(ctx context.Context, arg SetGatewayOutboxResultParams) (GatewayOutbox, error) {
	row := q.db.QueryRow(ctx, setGatewayOutboxResult,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Parts,
		arg.ID,
	)
	var i GatewayOutbox
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.MessageID,
		&i.ToAddress,
		&i.Text,
		&i.SimSlot,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Parts,
		&i.ExpiresAt,
		&i.LeasedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchGatewayDevice = `-- name: TouchGatewayDevice :exec
UPDATE gateway_devices SET last_seen_at = now(), device_info = $1, updated_at = now()
WHERE provider_id = $2
`

type TouchGatewayDeviceParams struct {
	DeviceInfo json.RawMessage
	ProviderID uuid.UUID
}

func (q *Queries) TouchGatewayDevice(ctx context.Context, arg TouchGatewayDeviceParams) error {
	_, err := q.db.Exec(ctx, touchGatewayDevice, arg.DeviceInfo, arg.ProviderID)
	return err
}

const upsertGatewayDevice = `-- name: UpsertGatewayDevice :one
INSERT INTO gateway_devices (provider_id, project_id, key_hash)
VALUES ($1, $2, $3)
ON CONFLICT (provider_id) DO UPDATE SET key_hash = EXCLUDED.key_hash, updated_at = now()
RETURNING provider_id, project_id, key_hash, last_seen_at, device_info, created_at, updated_at
`

type UpsertGatewayDeviceParams struct {
	ProviderID uuid.UUID
	ProjectID  uuid.UUID
	KeyHash    []byte
}

func (q *Queries) UpsertGatewayDevice(ctx context.Context, arg UpsertGatewayDeviceParams) (GatewayDevice, error) {
	row := q.db.QueryRow(ctx, upsertGatewayDevice, arg.ProviderID, arg.ProjectID, arg.KeyHash)
	var i GatewayDevice
	err := row.Scan(
		&i.ProviderID,
		&i.ProjectID,
		&i.KeyHash,
		&i.LastSeenAt,
		&i.DeviceInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
