// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: groups.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addGroupMembers = `-- name: AddGroupMembers :execrows
INSERT INTO contact_group_members (group_id, contact_id)
SELECT $1, c.id FROM contacts c
WHERE c.project_id = $2 AND c.id = ANY($3::uuid[])
ON CONFLICT DO NOTHING
`

type AddGroupMembersParams struct {
	GroupID    uuid.UUID
	ProjectID  uuid.UUID
	ContactIds []uuid.UUID
}

func (q *Queries) AddGroupMembers(ctx context.Context, arg AddGroupMembersParams) (int64, error) {
	result, err := q.db.Exec(ctx, addGroupMembers, arg.GroupID, arg.ProjectID, arg.ContactIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*)::bigint FROM contact_group_members WHERE group_id = $1
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, groupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO contact_groups (id, project_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, description, created_at, updated_at
`

type CreateGroupParams struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Description string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (ContactGroup, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
	)
	var i ContactGroup
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM contact_groups WHERE id = $1 AND project_id = $2
`

type DeleteGroupParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroup = `-- name: GetGroup :one
SELECT id, project_id, name, description, created_at, updated_at FROM contact_groups WHERE id = $1 AND project_id = $2
`

type GetGroupParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (ContactGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, arg.ID, arg.ProjectID)
	var i ContactGroup
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupContactIDs = `-- name: ListGroupContactIDs :many
SELECT m.contact_id FROM contact_group_members m
JOIN contact_groups g ON g.id = m.group_id
WHERE m.group_id = ANY($1::uuid[]) AND g.project_id = $2
`

type ListGroupContactIDsParams struct {
	GroupIds  []uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) ListGroupContactIDs(ctx context.Context, arg ListGroupContactIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listGroupContactIDs, arg.GroupIds, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var contact_id uuid.UUID
		if err := rows.Scan(&contact_id); err != nil {
			return nil, err
		}
		items = append(items, contact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT c.id, c.project_id, c.external_id, c.phone, c.email, c.telegram_chat_id, c.locale, c.tags, c.attributes, c.created_at, c.updated_at, c.name, c.whatsapp, c.slack_id FROM contacts c
JOIN contact_group_members m ON m.contact_id = c.id
WHERE m.group_id = $1
ORDER BY lower(c.name), c.created_at
LIMIT $3 OFFSET $2
`

type ListGroupMembersParams struct {
	GroupID   uuid.UUID
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, arg.GroupID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ExternalID,
			&i.Phone,
			&i.Email,
			&i.TelegramChatID,
			&i.Locale,
			&i.Tags,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Whatsapp,
			&i.SlackID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.project_id, g.name, g.description, g.created_at, g.updated_at, (SELECT count(*) FROM contact_group_members m WHERE m.group_id = g.id)::bigint AS member_count
FROM contact_groups g
WHERE g.project_id = $1
ORDER BY lower(g.name)
`

type ListGroupsRow struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	MemberCount int64
}

func (q *Queries) ListGroups(ctx context.Context, projectID uuid.UUID) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsRow{}
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForContact = `-- name: ListGroupsForContact :many
SELECT g.id, g.project_id, g.name, g.description, g.created_at, g.updated_at FROM contact_groups g
JOIN contact_group_members m ON m.group_id = g.id
WHERE m.contact_id = $1
ORDER BY lower(g.name)
`

func (q *Queries) ListGroupsForContact(ctx context.Context, contactID uuid.UUID) ([]ContactGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactGroup{}
	for rows.Next() {
		var i ContactGroup
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :execrows
DELETE FROM contact_group_members WHERE group_id = $1 AND contact_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID   uuid.UUID
	ContactID uuid.UUID
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.ContactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE contact_groups SET name = $1, description = $2, updated_at = now()
WHERE id = $3 AND project_id = $4
RETURNING id, project_id, name, description, created_at, updated_at
`

type UpdateGroupParams struct {
	Name        string
	Description string
	ID          uuid.UUID
	ProjectID   uuid.UUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (ContactGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.ProjectID,
	)
	var i ContactGroup
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
