// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cancelMessage = `-- name: CancelMessage :execrows
UPDATE messages SET status = 'cancelled', updated_at = now()
WHERE id = $1 AND project_id = $2 AND status = 'queued'
`

type CancelMessageParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) CancelMessage(ctx context.Context, arg CancelMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelMessage, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeBatchIfDone = `-- name: CompleteBatchIfDone :one
UPDATE batches b SET status = 'completed', completed_at = now()
WHERE b.id = $1 AND b.status = 'processing'
  AND NOT EXISTS (SELECT 1 FROM messages m WHERE m.batch_id = b.id AND m.status IN ('queued', 'processing'))
RETURNING b.id, b.project_id, b.template_key, b.channel, b.total, b.queued, b.sent, b.delivered, b.failed, b.status, b.idempotency_key, b.created_at, b.completed_at
`

func (q *Queries) CompleteBatchIfDone(ctx context.Context, id uuid.UUID) (Batch, error) {
	row := q.db.QueryRow(ctx, completeBatchIfDone, id)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateKey,
		&i.Channel,
		&i.Total,
		&i.Queued,
		&i.Sent,
		&i.Delivered,
		&i.Failed,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countMessagesSince = `-- name: CountMessagesSince :one
SELECT count(*) FROM messages
WHERE project_id = $1 AND created_at >= $2 AND status <> 'cancelled' AND NOT is_test
`

type CountMessagesSinceParams struct {
	ProjectID uuid.UUID
	Since     time.Time
}

func (q *Queries) CountMessagesSince(ctx context.Context, arg CountMessagesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesSince, arg.ProjectID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches (id, project_id, template_key, channel, total, queued, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $5, $6)
RETURNING id, project_id, template_key, channel, total, queued, sent, delivered, failed, status, idempotency_key, created_at, completed_at
`

type CreateBatchParams struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	TemplateKey    string
	Channel        Channel
	Total          int32
	IdempotencyKey *string
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, createBatch,
		arg.ID,
		arg.ProjectID,
		arg.TemplateKey,
		arg.Channel,
		arg.Total,
		arg.IdempotencyKey,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateKey,
		&i.Channel,
		&i.Total,
		&i.Queued,
		&i.Sent,
		&i.Delivered,
		&i.Failed,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version,
    rendered_subject, rendered_body, status, priority, scheduled_at, metadata, idempotency_key, is_test
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version, rendered_subject, rendered_body, status, priority, provider_id, provider_message_id, error_code, error_message, attempts, scheduled_at, sent_at, delivered_at, cost_micros, currency, metadata, idempotency_key, is_test, created_at, updated_at
`

type CreateMessageParams struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	BatchID         *uuid.UUID
	Channel         Channel
	ToAddress       string
	ContactID       *uuid.UUID
	TemplateKey     string
	TemplateVersion *int32
	RenderedSubject string
	RenderedBody    string
	Status          MessageStatus
	Priority        MessagePriority
	ScheduledAt     *time.Time
	Metadata        json.RawMessage
	IdempotencyKey  *string
	IsTest          bool
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ProjectID,
		arg.BatchID,
		arg.Channel,
		arg.ToAddress,
		arg.ContactID,
		arg.TemplateKey,
		arg.TemplateVersion,
		arg.RenderedSubject,
		arg.RenderedBody,
		arg.Status,
		arg.Priority,
		arg.ScheduledAt,
		arg.Metadata,
		arg.IdempotencyKey,
		arg.IsTest,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BatchID,
		&i.Channel,
		&i.ToAddress,
		&i.ContactID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.RenderedSubject,
		&i.RenderedBody,
		&i.Status,
		&i.Priority,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Attempts,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CostMicros,
		&i.Currency,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessageEvent = `-- name: CreateMessageEvent :one
INSERT INTO message_events (message_id, type, provider_id, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, message_id, type, provider_id, payload, created_at
`

type CreateMessageEventParams struct {
	MessageID  uuid.UUID
	Type       EventType
	ProviderID *uuid.UUID
	Payload    json.RawMessage
}

func (q *Queries) CreateMessageEvent(ctx context.Context, arg CreateMessageEventParams) (MessageEvent, error) {
	row := q.db.QueryRow(ctx, createMessageEvent,
		arg.MessageID,
		arg.Type,
		arg.ProviderID,
		arg.Payload,
	)
	var i MessageEvent
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Type,
		&i.ProviderID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM message_idempotency_keys WHERE created_at < $1
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureMessagesPartition = `-- name: EnsureMessagesPartition :one
SELECT ensure_messages_partition($1::date) AS partition_name
`

func (q *Queries) EnsureMessagesPartition(ctx context.Context, day time.Time) (string, error) {
	row := q.db.QueryRow(ctx, ensureMessagesPartition, day)
	var partition_name string
	err := row.Scan(&partition_name)
	return partition_name, err
}

const getBatch = `-- name: GetBatch :one
SELECT id, project_id, template_key, channel, total, queued, sent, delivered, failed, status, idempotency_key, created_at, completed_at FROM batches WHERE id = $1 AND project_id = $2
`

type GetBatchParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetBatch(ctx context.Context, arg GetBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, getBatch, arg.ID, arg.ProjectID)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateKey,
		&i.Channel,
		&i.Total,
		&i.Queued,
		&i.Sent,
		&i.Delivered,
		&i.Failed,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getBatchByIdempotencyKey = `-- name: GetBatchByIdempotencyKey :one
SELECT id, project_id, template_key, channel, total, queued, sent, delivered, failed, status, idempotency_key, created_at, completed_at FROM batches WHERE project_id = $1 AND idempotency_key = $2
`

type GetBatchByIdempotencyKeyParams struct {
	ProjectID      uuid.UUID
	IdempotencyKey *string
}

func (q *Queries) GetBatchByIdempotencyKey(ctx context.Context, arg GetBatchByIdempotencyKeyParams) (Batch, error) {
	row := q.db.QueryRow(ctx, getBatchByIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateKey,
		&i.Channel,
		&i.Total,
		&i.Queued,
		&i.Sent,
		&i.Delivered,
		&i.Failed,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT message_id FROM message_idempotency_keys WHERE project_id = $1 AND idempotency_key = $2
`

type GetIdempotencyKeyParams struct {
	ProjectID      uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var message_id uuid.UUID
	err := row.Scan(&message_id)
	return message_id, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version, rendered_subject, rendered_body, status, priority, provider_id, provider_message_id, error_code, error_message, attempts, scheduled_at, sent_at, delivered_at, cost_micros, currency, metadata, idempotency_key, is_test, created_at, updated_at FROM messages WHERE id = $1 AND project_id = $2
`

type GetMessageParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.ID, arg.ProjectID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BatchID,
		&i.Channel,
		&i.ToAddress,
		&i.ContactID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.RenderedSubject,
		&i.RenderedBody,
		&i.Status,
		&i.Priority,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Attempts,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CostMicros,
		&i.Currency,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version, rendered_subject, rendered_body, status, priority, provider_id, provider_message_id, error_code, error_message, attempts, scheduled_at, sent_at, delivered_at, cost_micros, currency, metadata, idempotency_key, is_test, created_at, updated_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BatchID,
		&i.Channel,
		&i.ToAddress,
		&i.ContactID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.RenderedSubject,
		&i.RenderedBody,
		&i.Status,
		&i.Priority,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Attempts,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CostMicros,
		&i.Currency,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByProviderMessageID = `-- name: GetMessageByProviderMessageID :one
SELECT id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version, rendered_subject, rendered_body, status, priority, provider_id, provider_message_id, error_code, error_message, attempts, scheduled_at, sent_at, delivered_at, cost_micros, currency, metadata, idempotency_key, is_test, created_at, updated_at FROM messages WHERE provider_id = $1 AND provider_message_id = $2
ORDER BY created_at DESC LIMIT 1
`

type GetMessageByProviderMessageIDParams struct {
	ProviderID        *uuid.UUID
	ProviderMessageID string
}

func (q *Queries) GetMessageByProviderMessageID(ctx context.Context, arg GetMessageByProviderMessageIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByProviderMessageID, arg.ProviderID, arg.ProviderMessageID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BatchID,
		&i.Channel,
		&i.ToAddress,
		&i.ContactID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.RenderedSubject,
		&i.RenderedBody,
		&i.Status,
		&i.Priority,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Attempts,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CostMicros,
		&i.Currency,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBatches = `-- name: ListBatches :many
SELECT id, project_id, template_key, channel, total, queued, sent, delivered, failed, status, idempotency_key, created_at, completed_at FROM batches WHERE project_id = $1 ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type ListBatchesParams struct {
	ProjectID uuid.UUID
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListBatches(ctx context.Context, arg ListBatchesParams) ([]Batch, error) {
	rows, err := q.db.Query(ctx, listBatches, arg.ProjectID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Batch{}
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TemplateKey,
			&i.Channel,
			&i.Total,
			&i.Queued,
			&i.Sent,
			&i.Delivered,
			&i.Failed,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueWebhookDeliveries = `-- name: ListDueWebhookDeliveries :many
SELECT id, project_id, message_id, batch_id, event, url, payload, signature, response_code, response_body, attempts, next_retry_at, delivered_at, created_at FROM webhook_deliveries
WHERE delivered_at IS NULL AND next_retry_at IS NOT NULL AND next_retry_at <= now()
ORDER BY next_retry_at LIMIT $1
`

func (q *Queries) ListDueWebhookDeliveries(ctx context.Context, rowLimit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDueWebhookDeliveries, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MessageID,
			&i.BatchID,
			&i.Event,
			&i.Url,
			&i.Payload,
			&i.Signature,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.Attempts,
			&i.NextRetryAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageEvents = `-- name: ListMessageEvents :many
SELECT id, message_id, type, provider_id, payload, created_at FROM message_events WHERE message_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListMessageEvents(ctx context.Context, messageID uuid.UUID) ([]MessageEvent, error) {
	rows, err := q.db.Query(ctx, listMessageEvents, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageEvent{}
	for rows.Next() {
		var i MessageEvent
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Type,
			&i.ProviderID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version, rendered_subject, rendered_body, status, priority, provider_id, provider_message_id, error_code, error_message, attempts, scheduled_at, sent_at, delivered_at, cost_micros, currency, metadata, idempotency_key, is_test, created_at, updated_at FROM messages
WHERE project_id = $1
  AND ($2::message_status IS NULL OR status = $2::message_status)
  AND ($3::channel IS NULL OR channel = $3::channel)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
  AND ($6::uuid IS NULL OR id < $6::uuid)
ORDER BY id DESC
LIMIT $7
`

type ListMessagesParams struct {
	ProjectID uuid.UUID
	Status    NullMessageStatus
	Channel   NullChannel
	FromTs    *time.Time
	ToTs      *time.Time
	CursorID  *uuid.UUID
	RowLimit  int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.ProjectID,
		arg.Status,
		arg.Channel,
		arg.FromTs,
		arg.ToTs,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BatchID,
			&i.Channel,
			&i.ToAddress,
			&i.ContactID,
			&i.TemplateKey,
			&i.TemplateVersion,
			&i.RenderedSubject,
			&i.RenderedBody,
			&i.Status,
			&i.Priority,
			&i.ProviderID,
			&i.ProviderMessageID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Attempts,
			&i.ScheduledAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.CostMicros,
			&i.Currency,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.IsTest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByBatch = `-- name: ListMessagesByBatch :many
SELECT id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version, rendered_subject, rendered_body, status, priority, provider_id, provider_message_id, error_code, error_message, attempts, scheduled_at, sent_at, delivered_at, cost_micros, currency, metadata, idempotency_key, is_test, created_at, updated_at FROM messages WHERE batch_id = $1 ORDER BY id LIMIT $3 OFFSET $2
`

type ListMessagesByBatchParams struct {
	BatchID   *uuid.UUID
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListMessagesByBatch(ctx context.Context, arg ListMessagesByBatchParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByBatch, arg.BatchID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BatchID,
			&i.Channel,
			&i.ToAddress,
			&i.ContactID,
			&i.TemplateKey,
			&i.TemplateVersion,
			&i.RenderedSubject,
			&i.RenderedBody,
			&i.Status,
			&i.Priority,
			&i.ProviderID,
			&i.ProviderMessageID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Attempts,
			&i.ScheduledAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.CostMicros,
			&i.Currency,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.IsTest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageDelivered = `-- name: MarkMessageDelivered :execrows
UPDATE messages SET status = 'delivered', delivered_at = now(), updated_at = now()
WHERE id = $1 AND status = 'sent'
`

func (q *Queries) MarkMessageDelivered(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markMessageDelivered, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markMessageFailed = `-- name: MarkMessageFailed :exec
UPDATE messages SET
    status        = 'failed',
    provider_id   = COALESCE($1, provider_id),
    error_code    = $2,
    error_message = $3,
    updated_at    = now()
WHERE id = $4
`

type MarkMessageFailedParams struct {
	ProviderID   *uuid.UUID
	ErrorCode    string
	ErrorMessage string
	ID           uuid.UUID
}

func (q *Queries) MarkMessageFailed(ctx context.Context, arg MarkMessageFailedParams) error {
	_, err := q.db.Exec(ctx, markMessageFailed,
		arg.ProviderID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const markMessageProcessing = `-- name: MarkMessageProcessing :one
UPDATE messages SET status = 'processing', attempts = attempts + 1, updated_at = now()
WHERE id = $1 AND status IN ('queued', 'processing')
RETURNING id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version, rendered_subject, rendered_body, status, priority, provider_id, provider_message_id, error_code, error_message, attempts, scheduled_at, sent_at, delivered_at, cost_micros, currency, metadata, idempotency_key, is_test, created_at, updated_at
`

func (q *Queries) MarkMessageProcessing(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, markMessageProcessing, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BatchID,
		&i.Channel,
		&i.ToAddress,
		&i.ContactID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.RenderedSubject,
		&i.RenderedBody,
		&i.Status,
		&i.Priority,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Attempts,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CostMicros,
		&i.Currency,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMessageSent = `-- name: MarkMessageSent :exec
UPDATE messages SET
    status              = 'sent',
    provider_id         = $1,
    provider_message_id = $2,
    cost_micros         = $3,
    currency            = $4,
    error_code          = '',
    error_message       = '',
    sent_at             = now(),
    updated_at          = now()
WHERE id = $5
`

type MarkMessageSentParams struct {
	ProviderID        *uuid.UUID
	ProviderMessageID string
	CostMicros        int64
	Currency          string
	ID                uuid.UUID
}

func (q *Queries) MarkMessageSent(ctx context.Context, arg MarkMessageSentParams) error {
	_, err := q.db.Exec(ctx, markMessageSent,
		arg.ProviderID,
		arg.ProviderMessageID,
		arg.CostMicros,
		arg.Currency,
		arg.ID,
	)
	return err
}

const refreshBatchCounters = `-- name: RefreshBatchCounters :one
UPDATE batches b SET
    queued    = s.queued,
    sent      = s.sent,
    delivered = s.delivered,
    failed    = s.failed
FROM (
    SELECT
        count(*) FILTER (WHERE status IN ('queued', 'processing'))::int AS queued,
        count(*) FILTER (WHERE status = 'sent')::int                    AS sent,
        count(*) FILTER (WHERE status = 'delivered')::int               AS delivered,
        count(*) FILTER (WHERE status IN ('failed', 'cancelled'))::int  AS failed
    FROM messages WHERE batch_id = $1
) s
WHERE b.id = $1
RETURNING b.id, b.project_id, b.template_key, b.channel, b.total, b.queued, b.sent, b.delivered, b.failed, b.status, b.idempotency_key, b.created_at, b.completed_at
`

// Counters only; the processing -> completed transition is done once by
// CompleteBatchIfDone so the batch.completed webhook fires exactly once.
func (q *Queries) RefreshBatchCounters(ctx context.Context, id uuid.UUID) (Batch, error) {
	row := q.db.QueryRow(ctx, refreshBatchCounters, id)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TemplateKey,
		&i.Channel,
		&i.Total,
		&i.Queued,
		&i.Sent,
		&i.Delivered,
		&i.Failed,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const requeueMessage = `-- name: RequeueMessage :exec
UPDATE messages SET status = 'queued', error_code = $1, error_message = $2, updated_at = now()
WHERE id = $3
`

type RequeueMessageParams struct {
	ErrorCode    string
	ErrorMessage string
	ID           uuid.UUID
}

func (q *Queries) RequeueMessage(ctx context.Context, arg RequeueMessageParams) error {
	_, err := q.db.Exec(ctx, requeueMessage, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	return err
}

const reserveIdempotencyKey = `-- name: ReserveIdempotencyKey :one
INSERT INTO message_idempotency_keys (project_id, idempotency_key, message_id)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, idempotency_key) DO NOTHING
RETURNING message_id
`

type ReserveIdempotencyKeyParams struct {
	ProjectID      uuid.UUID
	IdempotencyKey string
	MessageID      uuid.UUID
}

func (q *Queries) ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, reserveIdempotencyKey, arg.ProjectID, arg.IdempotencyKey, arg.MessageID)
	var message_id uuid.UUID
	err := row.Scan(&message_id)
	return message_id, err
}

const resetMessageForResend = `-- name: ResetMessageForResend :one
UPDATE messages SET
    status = 'queued', attempts = 0, provider_id = NULL, provider_message_id = '',
    error_code = '', error_message = '', sent_at = NULL, delivered_at = NULL, updated_at = now()
WHERE id = $1 AND project_id = $2 AND status IN ('failed', 'cancelled')
RETURNING id, project_id, batch_id, channel, to_address, contact_id, template_key, template_version, rendered_subject, rendered_body, status, priority, provider_id, provider_message_id, error_code, error_message, attempts, scheduled_at, sent_at, delivered_at, cost_micros, currency, metadata, idempotency_key, is_test, created_at, updated_at
`

type ResetMessageForResendParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) ResetMessageForResend(ctx context.Context, arg ResetMessageForResendParams) (Message, error) {
	row := q.db.QueryRow(ctx, resetMessageForResend, arg.ID, arg.ProjectID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BatchID,
		&i.Channel,
		&i.ToAddress,
		&i.ContactID,
		&i.TemplateKey,
		&i.TemplateVersion,
		&i.RenderedSubject,
		&i.RenderedBody,
		&i.Status,
		&i.Priority,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Attempts,
		&i.ScheduledAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CostMicros,
		&i.Currency,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
