// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Channel string

const (
	ChannelSms      Channel = "sms"
	ChannelEmail    Channel = "email"
	ChannelPush     Channel = "push"
	ChannelTelegram Channel = "telegram"
	ChannelWhatsapp Channel = "whatsapp"
	ChannelSlack    Channel = "slack"
)

func (e *Channel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Channel(s)
	case string:
		*e = Channel(s)
	default:
		return fmt.Errorf("unsupported scan type for Channel: %T", src)
	}
	return nil
}

type NullChannel struct {
	Channel Channel
	Valid   bool // Valid is true if Channel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannel) Scan(value interface{}) error {
	if value == nil {
		ns.Channel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Channel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Channel), nil
}

func (e Channel) Valid() bool {
	switch e {
	case ChannelSms,
		ChannelEmail,
		ChannelPush,
		ChannelTelegram,
		ChannelWhatsapp,
		ChannelSlack:
		return true
	}
	return false
}

func AllChannelValues() []Channel {
	return []Channel{
		ChannelSms,
		ChannelEmail,
		ChannelPush,
		ChannelTelegram,
		ChannelWhatsapp,
		ChannelSlack,
	}
}

type DevicePlatform string

const (
	DevicePlatformAndroid DevicePlatform = "android"
	DevicePlatformIos     DevicePlatform = "ios"
	DevicePlatformWeb     DevicePlatform = "web"
)

func (e *DevicePlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DevicePlatform(s)
	case string:
		*e = DevicePlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for DevicePlatform: %T", src)
	}
	return nil
}

type NullDevicePlatform struct {
	DevicePlatform DevicePlatform
	Valid          bool // Valid is true if DevicePlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDevicePlatform) Scan(value interface{}) error {
	if value == nil {
		ns.DevicePlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DevicePlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDevicePlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DevicePlatform), nil
}

func (e DevicePlatform) Valid() bool {
	switch e {
	case DevicePlatformAndroid,
		DevicePlatformIos,
		DevicePlatformWeb:
		return true
	}
	return false
}

func AllDevicePlatformValues() []DevicePlatform {
	return []DevicePlatform{
		DevicePlatformAndroid,
		DevicePlatformIos,
		DevicePlatformWeb,
	}
}

type EventType string

const (
	EventTypeQueued           EventType = "queued"
	EventTypeAttempt          EventType = "attempt"
	EventTypeProviderResponse EventType = "provider_response"
	EventTypeSent             EventType = "sent"
	EventTypeDelivered        EventType = "delivered"
	EventTypeFailed           EventType = "failed"
	EventTypeCancelled        EventType = "cancelled"
	EventTypeWebhookSent      EventType = "webhook_sent"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType
	Valid     bool // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

func (e EventType) Valid() bool {
	switch e {
	case EventTypeQueued,
		EventTypeAttempt,
		EventTypeProviderResponse,
		EventTypeSent,
		EventTypeDelivered,
		EventTypeFailed,
		EventTypeCancelled,
		EventTypeWebhookSent:
		return true
	}
	return false
}

func AllEventTypeValues() []EventType {
	return []EventType{
		EventTypeQueued,
		EventTypeAttempt,
		EventTypeProviderResponse,
		EventTypeSent,
		EventTypeDelivered,
		EventTypeFailed,
		EventTypeCancelled,
		EventTypeWebhookSent,
	}
}

type MemberRole string

const (
	MemberRoleOwner     MemberRole = "owner"
	MemberRoleAdmin     MemberRole = "admin"
	MemberRoleDeveloper MemberRole = "developer"
	MemberRoleViewer    MemberRole = "viewer"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

func (e MemberRole) Valid() bool {
	switch e {
	case MemberRoleOwner,
		MemberRoleAdmin,
		MemberRoleDeveloper,
		MemberRoleViewer:
		return true
	}
	return false
}

func AllMemberRoleValues() []MemberRole {
	return []MemberRole{
		MemberRoleOwner,
		MemberRoleAdmin,
		MemberRoleDeveloper,
		MemberRoleViewer,
	}
}

type MessagePriority string

const (
	MessagePriorityHigh   MessagePriority = "high"
	MessagePriorityNormal MessagePriority = "normal"
	MessagePriorityLow    MessagePriority = "low"
)

func (e *MessagePriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessagePriority(s)
	case string:
		*e = MessagePriority(s)
	default:
		return fmt.Errorf("unsupported scan type for MessagePriority: %T", src)
	}
	return nil
}

type NullMessagePriority struct {
	MessagePriority MessagePriority
	Valid           bool // Valid is true if MessagePriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessagePriority) Scan(value interface{}) error {
	if value == nil {
		ns.MessagePriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessagePriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessagePriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessagePriority), nil
}

func (e MessagePriority) Valid() bool {
	switch e {
	case MessagePriorityHigh,
		MessagePriorityNormal,
		MessagePriorityLow:
		return true
	}
	return false
}

func AllMessagePriorityValues() []MessagePriority {
	return []MessagePriority{
		MessagePriorityHigh,
		MessagePriorityNormal,
		MessagePriorityLow,
	}
}

type MessageStatus string

const (
	MessageStatusQueued     MessageStatus = "queued"
	MessageStatusProcessing MessageStatus = "processing"
	MessageStatusSent       MessageStatus = "sent"
	MessageStatusDelivered  MessageStatus = "delivered"
	MessageStatusFailed     MessageStatus = "failed"
	MessageStatusCancelled  MessageStatus = "cancelled"
)

func (e *MessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageStatus(s)
	case string:
		*e = MessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageStatus: %T", src)
	}
	return nil
}

type NullMessageStatus struct {
	MessageStatus MessageStatus
	Valid         bool // Valid is true if MessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageStatus), nil
}

func (e MessageStatus) Valid() bool {
	switch e {
	case MessageStatusQueued,
		MessageStatusProcessing,
		MessageStatusSent,
		MessageStatusDelivered,
		MessageStatusFailed,
		MessageStatusCancelled:
		return true
	}
	return false
}

func AllMessageStatusValues() []MessageStatus {
	return []MessageStatus{
		MessageStatusQueued,
		MessageStatusProcessing,
		MessageStatusSent,
		MessageStatusDelivered,
		MessageStatusFailed,
		MessageStatusCancelled,
	}
}

type ProjectStatus string

const (
	ProjectStatusActive    ProjectStatus = "active"
	ProjectStatusSuspended ProjectStatus = "suspended"
	ProjectStatusArchived  ProjectStatus = "archived"
)

func (e *ProjectStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectStatus(s)
	case string:
		*e = ProjectStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectStatus: %T", src)
	}
	return nil
}

type NullProjectStatus struct {
	ProjectStatus ProjectStatus
	Valid         bool // Valid is true if ProjectStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectStatus), nil
}

func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusActive,
		ProjectStatusSuspended,
		ProjectStatusArchived:
		return true
	}
	return false
}

func AllProjectStatusValues() []ProjectStatus {
	return []ProjectStatus{
		ProjectStatusActive,
		ProjectStatusSuspended,
		ProjectStatusArchived,
	}
}

type ProviderType string

const (
	ProviderTypeHttpSms       ProviderType = "http_sms"
	ProviderTypeSmpp          ProviderType = "smpp"
	ProviderTypeSmtp          ProviderType = "smtp"
	ProviderTypeFcm           ProviderType = "fcm"
	ProviderTypeTelegramBot   ProviderType = "telegram_bot"
	ProviderTypeAndroidSms    ProviderType = "android_sms"
	ProviderTypeWhatsappCloud ProviderType = "whatsapp_cloud"
	ProviderTypeSlack         ProviderType = "slack"
)

func (e *ProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderType(s)
	case string:
		*e = ProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderType: %T", src)
	}
	return nil
}

type NullProviderType struct {
	ProviderType ProviderType
	Valid        bool // Valid is true if ProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderType), nil
}

func (e ProviderType) Valid() bool {
	switch e {
	case ProviderTypeHttpSms,
		ProviderTypeSmpp,
		ProviderTypeSmtp,
		ProviderTypeFcm,
		ProviderTypeTelegramBot,
		ProviderTypeAndroidSms,
		ProviderTypeWhatsappCloud,
		ProviderTypeSlack:
		return true
	}
	return false
}

func AllProviderTypeValues() []ProviderType {
	return []ProviderType{
		ProviderTypeHttpSms,
		ProviderTypeSmpp,
		ProviderTypeSmtp,
		ProviderTypeFcm,
		ProviderTypeTelegramBot,
		ProviderTypeAndroidSms,
		ProviderTypeWhatsappCloud,
		ProviderTypeSlack,
	}
}

type ApiKey struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Name             string
	Prefix           string
	Hint             string
	KeyHash          []byte
	Scopes           []string
	IpAllowlist      []string
	LastUsedAt       *time.Time
	ExpiresAt        *time.Time
	RevokedAt        *time.Time
	CreatedAt        time.Time
	RequireSignature bool
}

type AuditLog struct {
	ID         uuid.UUID
	ProjectID  *uuid.UUID
	UserID     *uuid.UUID
	Action     string
	EntityType string
	EntityID   string
	Changes    json.RawMessage
	Ip         string
	UserAgent  string
	CreatedAt  time.Time
}

type Batch struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	TemplateKey    string
	Channel        Channel
	Total          int32
	Queued         int32
	Sent           int32
	Delivered      int32
	Failed         int32
	Status         string
	IdempotencyKey *string
	CreatedAt      time.Time
	CompletedAt    *time.Time
}

type Contact struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	ExternalID     string
	Phone          string
	Email          string
	TelegramChatID string
	Locale         string
	Tags           []string
	Attributes     json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Whatsapp       string
	SlackID        string
}

type ContactGroup struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ContactGroupMember struct {
	GroupID   uuid.UUID
	ContactID uuid.UUID
	AddedAt   time.Time
}

type Device struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	ContactID  *uuid.UUID
	Platform   DevicePlatform
	FcmToken   string
	AppVersion string
	LastSeenAt time.Time
	IsActive   bool
	CreatedAt  time.Time
}

type GatewayDevice struct {
	ProviderID uuid.UUID
	ProjectID  uuid.UUID
	KeyHash    []byte
	LastSeenAt *time.Time
	DeviceInfo json.RawMessage
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type GatewayInbound struct {
	ID          uuid.UUID
	ProviderID  uuid.UUID
	ProjectID   uuid.UUID
	FromAddress string
	Text        string
	ReceivedAt  time.Time
	CreatedAt   time.Time
}

type GatewayOutbox struct {
	ID           uuid.UUID
	ProviderID   uuid.UUID
	MessageID    uuid.UUID
	ToAddress    string
	Text         string
	SimSlot      int32
	Status       string
	ErrorCode    string
	ErrorMessage string
	Parts        int32
	ExpiresAt    time.Time
	LeasedAt     *time.Time
	SentAt       *time.Time
	DeliveredAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Message struct {
	ID                uuid.UUID
	ProjectID         uuid.UUID
	BatchID           *uuid.UUID
	Channel           Channel
	ToAddress         string
	ContactID         *uuid.UUID
	TemplateKey       string
	TemplateVersion   *int32
	RenderedSubject   string
	RenderedBody      string
	Status            MessageStatus
	Priority          MessagePriority
	ProviderID        *uuid.UUID
	ProviderMessageID string
	ErrorCode         string
	ErrorMessage      string
	Attempts          int32
	ScheduledAt       *time.Time
	SentAt            *time.Time
	DeliveredAt       *time.Time
	CostMicros        int64
	Currency          string
	Metadata          json.RawMessage
	IdempotencyKey    *string
	IsTest            bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type MessageEvent struct {
	ID         uuid.UUID
	MessageID  uuid.UUID
	Type       EventType
	ProviderID *uuid.UUID
	Payload    json.RawMessage
	CreatedAt  time.Time
}

type MessageIdempotencyKey struct {
	ProjectID      uuid.UUID
	IdempotencyKey string
	MessageID      uuid.UUID
	CreatedAt      time.Time
}

type Project struct {
	ID               uuid.UUID
	Name             string
	Slug             string
	Status           ProjectStatus
	DailyQuota       int64
	MonthlyQuota     int64
	WebhookUrl       string
	WebhookSecretEnc []byte
	DefaultLocale    string
	AllowedIps       []string
	AutoChannelOrder []Channel
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ProjectMember struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      MemberRole
	CreatedAt time.Time
}

type Provider struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	Name            string
	Channel         Channel
	Type            ProviderType
	Priority        int32
	IsActive        bool
	CredentialsEnc  []byte
	RateLimitPerSec int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	UserAgent  string
	Ip         string
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	ReplacedBy *uuid.UUID
	CreatedAt  time.Time
}

type Template struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	Key          string
	Channel      Channel
	Locale       string
	Subject      string
	Body         string
	RequiredVars []string
	Version      int32
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TemplateVersion struct {
	ID           uuid.UUID
	TemplateID   uuid.UUID
	Version      int32
	Subject      string
	Body         string
	RequiredVars []string
	CreatedBy    *uuid.UUID
	CreatedAt    time.Time
}

type UsageDaily struct {
	ProjectID  uuid.UUID
	Day        time.Time
	Channel    Channel
	Queued     int64
	Sent       int64
	Delivered  int64
	Failed     int64
	CostMicros int64
	Currency   string
}

type User struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  string
	FullName      string
	IsActive      bool
	TotpEnabled   bool
	TotpSecretEnc []byte
	LastLoginAt   *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type WebhookDelivery struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	MessageID    *uuid.UUID
	BatchID      *uuid.UUID
	Event        string
	Url          string
	Payload      json.RawMessage
	Signature    string
	ResponseCode *int32
	ResponseBody string
	Attempts     int32
	NextRetryAt  *time.Time
	DeliveredAt  *time.Time
	CreatedAt    time.Time
}
