// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countProjectOwners = `-- name: CountProjectOwners :one
SELECT count(*) FROM project_members WHERE project_id = $1 AND role = 'owner'
`

func (q *Queries) CountProjectOwners(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectOwners, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, slug, daily_quota, monthly_quota, default_locale)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, status, daily_quota, monthly_quota, webhook_url, webhook_secret_enc, default_locale, allowed_ips, auto_channel_order, created_at, updated_at
`

type CreateProjectParams struct {
	Name          string
	Slug          string
	DailyQuota    int64
	MonthlyQuota  int64
	DefaultLocale string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Slug,
		arg.DailyQuota,
		arg.MonthlyQuota,
		arg.DefaultLocale,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.DailyQuota,
		&i.MonthlyQuota,
		&i.WebhookUrl,
		&i.WebhookSecretEnc,
		&i.DefaultLocale,
		&i.AllowedIps,
		&i.AutoChannelOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, slug, status, daily_quota, monthly_quota, webhook_url, webhook_secret_enc, default_locale, allowed_ips, auto_channel_order, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.DailyQuota,
		&i.MonthlyQuota,
		&i.WebhookUrl,
		&i.WebhookSecretEnc,
		&i.DefaultLocale,
		&i.AllowedIps,
		&i.AutoChannelOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, slug, status, daily_quota, monthly_quota, webhook_url, webhook_secret_enc, default_locale, allowed_ips, auto_channel_order, created_at, updated_at FROM projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.DailyQuota,
		&i.MonthlyQuota,
		&i.WebhookUrl,
		&i.WebhookSecretEnc,
		&i.DefaultLocale,
		&i.AllowedIps,
		&i.AutoChannelOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, role, created_at FROM project_members WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT m.project_id, m.user_id, m.role, m.created_at, u.email, u.full_name
FROM project_members m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = $1
ORDER BY m.created_at
`

type ListProjectMembersRow struct {
	ProjectMember ProjectMember
	Email         string
	FullName      string
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectMember.ProjectID,
			&i.ProjectMember.UserID,
			&i.ProjectMember.Role,
			&i.ProjectMember.CreatedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, slug, status, daily_quota, monthly_quota, webhook_url, webhook_secret_enc, default_locale, allowed_ips, auto_channel_order, created_at, updated_at FROM projects ORDER BY created_at DESC LIMIT $2 OFFSET $1
`

type ListProjectsParams struct {
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.DailyQuota,
			&i.MonthlyQuota,
			&i.WebhookUrl,
			&i.WebhookSecretEnc,
			&i.DefaultLocale,
			&i.AllowedIps,
			&i.AutoChannelOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.name, p.slug, p.status, p.daily_quota, p.monthly_quota, p.webhook_url, p.webhook_secret_enc, p.default_locale, p.allowed_ips, p.auto_channel_order, p.created_at, p.updated_at, m.role
FROM projects p
JOIN project_members m ON m.project_id = p.id
WHERE m.user_id = $1
ORDER BY p.created_at DESC
`

type ListProjectsForUserRow struct {
	Project Project
	Role    MemberRole
}

func (q *Queries) ListProjectsForUser(ctx context.Context, userID uuid.UUID) ([]ListProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsForUserRow{}
	for rows.Next() {
		var i ListProjectsForUserRow
		if err := rows.Scan(
			&i.Project.ID,
			&i.Project.Name,
			&i.Project.Slug,
			&i.Project.Status,
			&i.Project.DailyQuota,
			&i.Project.MonthlyQuota,
			&i.Project.WebhookUrl,
			&i.Project.WebhookSecretEnc,
			&i.Project.DefaultLocale,
			&i.Project.AllowedIps,
			&i.Project.AutoChannelOrder,
			&i.Project.CreatedAt,
			&i.Project.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const setProjectWebhookSecret = `-- name: SetProjectWebhookSecret :exec
UPDATE projects SET webhook_secret_enc = $1, updated_at = now() WHERE id = $2
`

type SetProjectWebhookSecretParams struct {
	WebhookSecretEnc []byte
	ID               uuid.UUID
}

func (q *Queries) SetProjectWebhookSecret(ctx context.Context, arg SetProjectWebhookSecretParams) error {
	_, err := q.db.Exec(ctx, setProjectWebhookSecret, arg.WebhookSecretEnc, arg.ID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name               = $1,
    status             = $2,
    daily_quota        = $3,
    monthly_quota      = $4,
    webhook_url        = $5,
    default_locale     = $6,
    allowed_ips        = $7,
    auto_channel_order = $8,
    updated_at         = now()
WHERE id = $9
RETURNING id, name, slug, status, daily_quota, monthly_quota, webhook_url, webhook_secret_enc, default_locale, allowed_ips, auto_channel_order, created_at, updated_at
`

type UpdateProjectParams struct {
	Name             string
	Status           ProjectStatus
	DailyQuota       int64
	MonthlyQuota     int64
	WebhookUrl       string
	DefaultLocale    string
	AllowedIps       []string
	AutoChannelOrder []Channel
	ID               uuid.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Status,
		arg.DailyQuota,
		arg.MonthlyQuota,
		arg.WebhookUrl,
		arg.DefaultLocale,
		arg.AllowedIps,
		arg.AutoChannelOrder,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.DailyQuota,
		&i.MonthlyQuota,
		&i.WebhookUrl,
		&i.WebhookSecretEnc,
		&i.DefaultLocale,
		&i.AllowedIps,
		&i.AutoChannelOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectMember = `-- name: UpsertProjectMember :one
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING project_id, user_id, role, created_at
`

type UpsertProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      MemberRole
}

func (q *Queries) UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, upsertProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
