// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: providers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (project_id, name, channel, type, priority, is_active, credentials_enc, rate_limit_per_sec)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, name, channel, type, priority, is_active, credentials_enc, rate_limit_per_sec, created_at, updated_at
`

type CreateProviderParams struct {
	ProjectID       uuid.UUID
	Name            string
	Channel         Channel
	Type            ProviderType
	Priority        int32
	IsActive        bool
	CredentialsEnc  []byte
	RateLimitPerSec int32
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.ProjectID,
		arg.Name,
		arg.Channel,
		arg.Type,
		arg.Priority,
		arg.IsActive,
		arg.CredentialsEnc,
		arg.RateLimitPerSec,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Channel,
		&i.Type,
		&i.Priority,
		&i.IsActive,
		&i.CredentialsEnc,
		&i.RateLimitPerSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM providers WHERE id = $1 AND project_id = $2
`

type DeleteProviderParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteProvider(ctx context.Context, arg DeleteProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvider, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProvider = `-- name: GetProvider :one
SELECT id, project_id, name, channel, type, priority, is_active, credentials_enc, rate_limit_per_sec, created_at, updated_at FROM providers WHERE id = $1 AND project_id = $2
`

type GetProviderParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetProvider(ctx context.Context, arg GetProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, arg.ID, arg.ProjectID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Channel,
		&i.Type,
		&i.Priority,
		&i.IsActive,
		&i.CredentialsEnc,
		&i.RateLimitPerSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, project_id, name, channel, type, priority, is_active, credentials_enc, rate_limit_per_sec, created_at, updated_at FROM providers WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Channel,
		&i.Type,
		&i.Priority,
		&i.IsActive,
		&i.CredentialsEnc,
		&i.RateLimitPerSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProvidersForChannel = `-- name: ListActiveProvidersForChannel :many
SELECT id, project_id, name, channel, type, priority, is_active, credentials_enc, rate_limit_per_sec, created_at, updated_at FROM providers
WHERE project_id = $1 AND channel = $2 AND is_active
ORDER BY priority, created_at
`

type ListActiveProvidersForChannelParams struct {
	ProjectID uuid.UUID
	Channel   Channel
}

func (q *Queries) ListActiveProvidersForChannel(ctx context.Context, arg ListActiveProvidersForChannelParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listActiveProvidersForChannel, arg.ProjectID, arg.Channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Channel,
			&i.Type,
			&i.Priority,
			&i.IsActive,
			&i.CredentialsEnc,
			&i.RateLimitPerSec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, project_id, name, channel, type, priority, is_active, credentials_enc, rate_limit_per_sec, created_at, updated_at FROM providers WHERE project_id = $1 ORDER BY channel, priority, created_at
`

func (q *Queries) ListProviders(ctx context.Context, projectID uuid.UUID) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Channel,
			&i.Type,
			&i.Priority,
			&i.IsActive,
			&i.CredentialsEnc,
			&i.RateLimitPerSec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers SET
    name               = $1,
    priority           = $2,
    is_active          = $3,
    credentials_enc    = $4,
    rate_limit_per_sec = $5,
    updated_at         = now()
WHERE id = $6 AND project_id = $7
RETURNING id, project_id, name, channel, type, priority, is_active, credentials_enc, rate_limit_per_sec, created_at, updated_at
`

type UpdateProviderParams struct {
	Name            string
	Priority        int32
	IsActive        bool
	CredentialsEnc  []byte
	RateLimitPerSec int32
	ID              uuid.UUID
	ProjectID       uuid.UUID
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.Name,
		arg.Priority,
		arg.IsActive,
		arg.CredentialsEnc,
		arg.RateLimitPerSec,
		arg.ID,
		arg.ProjectID,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Channel,
		&i.Type,
		&i.Priority,
		&i.IsActive,
		&i.CredentialsEnc,
		&i.RateLimitPerSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
