// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: templates.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (project_id, key, channel, locale, subject, body, required_vars)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, key, channel, locale, subject, body, required_vars, version, is_active, created_at, updated_at
`

type CreateTemplateParams struct {
	ProjectID    uuid.UUID
	Key          string
	Channel      Channel
	Locale       string
	Subject      string
	Body         string
	RequiredVars []string
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.ProjectID,
		arg.Key,
		arg.Channel,
		arg.Locale,
		arg.Subject,
		arg.Body,
		arg.RequiredVars,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Channel,
		&i.Locale,
		&i.Subject,
		&i.Body,
		&i.RequiredVars,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplateVersion = `-- name: CreateTemplateVersion :one
INSERT INTO template_versions (template_id, version, subject, body, required_vars, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, template_id, version, subject, body, required_vars, created_by, created_at
`

type CreateTemplateVersionParams struct {
	TemplateID   uuid.UUID
	Version      int32
	Subject      string
	Body         string
	RequiredVars []string
	CreatedBy    *uuid.UUID
}

func (q *Queries) CreateTemplateVersion(ctx context.Context, arg CreateTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRow(ctx, createTemplateVersion,
		arg.TemplateID,
		arg.Version,
		arg.Subject,
		arg.Body,
		arg.RequiredVars,
		arg.CreatedBy,
	)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Version,
		&i.Subject,
		&i.Body,
		&i.RequiredVars,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE FROM templates WHERE id = $1 AND project_id = $2
`

type DeleteTemplateParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findTemplate = `-- name: FindTemplate :one
SELECT id, project_id, key, channel, locale, subject, body, required_vars, version, is_active, created_at, updated_at FROM templates
WHERE project_id = $1 AND key = $2 AND channel = $3 AND locale = $4 AND is_active
`

type FindTemplateParams struct {
	ProjectID uuid.UUID
	Key       string
	Channel   Channel
	Locale    string
}

func (q *Queries) FindTemplate(ctx context.Context, arg FindTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, findTemplate,
		arg.ProjectID,
		arg.Key,
		arg.Channel,
		arg.Locale,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Channel,
		&i.Locale,
		&i.Subject,
		&i.Body,
		&i.RequiredVars,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, project_id, key, channel, locale, subject, body, required_vars, version, is_active, created_at, updated_at FROM templates WHERE id = $1 AND project_id = $2
`

type GetTemplateParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, arg.ID, arg.ProjectID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Channel,
		&i.Locale,
		&i.Subject,
		&i.Body,
		&i.RequiredVars,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateVersion = `-- name: GetTemplateVersion :one
SELECT id, template_id, version, subject, body, required_vars, created_by, created_at FROM template_versions WHERE template_id = $1 AND version = $2
`

type GetTemplateVersionParams struct {
	TemplateID uuid.UUID
	Version    int32
}

func (q *Queries) GetTemplateVersion(ctx context.Context, arg GetTemplateVersionParams) (TemplateVersion, error) {
	row := q.db.QueryRow(ctx, getTemplateVersion, arg.TemplateID, arg.Version)
	var i TemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Version,
		&i.Subject,
		&i.Body,
		&i.RequiredVars,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listTemplateVersions = `-- name: ListTemplateVersions :many
SELECT id, template_id, version, subject, body, required_vars, created_by, created_at FROM template_versions WHERE template_id = $1 ORDER BY version DESC
`

func (q *Queries) ListTemplateVersions(ctx context.Context, templateID uuid.UUID) ([]TemplateVersion, error) {
	rows, err := q.db.Query(ctx, listTemplateVersions, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateVersion{}
	for rows.Next() {
		var i TemplateVersion
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Version,
			&i.Subject,
			&i.Body,
			&i.RequiredVars,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, project_id, key, channel, locale, subject, body, required_vars, version, is_active, created_at, updated_at FROM templates WHERE project_id = $1 ORDER BY key, channel, locale
`

func (q *Queries) ListTemplates(ctx context.Context, projectID uuid.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Channel,
			&i.Locale,
			&i.Subject,
			&i.Body,
			&i.RequiredVars,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByKey = `-- name: ListTemplatesByKey :many
SELECT id, project_id, key, channel, locale, subject, body, required_vars, version, is_active, created_at, updated_at FROM templates WHERE project_id = $1 AND key = $2 ORDER BY channel, locale
`

type ListTemplatesByKeyParams struct {
	ProjectID uuid.UUID
	Key       string
}

func (q *Queries) ListTemplatesByKey(ctx context.Context, arg ListTemplatesByKeyParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByKey, arg.ProjectID, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Channel,
			&i.Locale,
			&i.Subject,
			&i.Body,
			&i.RequiredVars,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates SET
    subject       = $1,
    body          = $2,
    required_vars = $3,
    is_active     = $4,
    version       = version + 1,
    updated_at    = now()
WHERE id = $5 AND project_id = $6
RETURNING id, project_id, key, channel, locale, subject, body, required_vars, version, is_active, created_at, updated_at
`

type UpdateTemplateParams struct {
	Subject      string
	Body         string
	RequiredVars []string
	IsActive     bool
	ID           uuid.UUID
	ProjectID    uuid.UUID
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Subject,
		arg.Body,
		arg.RequiredVars,
		arg.IsActive,
		arg.ID,
		arg.ProjectID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Channel,
		&i.Locale,
		&i.Subject,
		&i.Body,
		&i.RequiredVars,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
