// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, user_agent, ip, expires_at, revoked_at, replaced_by, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	UserAgent string
	Ip        string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name)
VALUES (lower($1), $2, $3)
RETURNING id, email, password_hash, full_name, is_active, totp_enabled, totp_secret_enc, last_login_at, created_at, updated_at, bio, avatar_id
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	FullName     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.TotpEnabled,
		&i.TotpSecretEnc,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarID,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, user_agent, ip, expires_at, revoked_at, replaced_by, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, is_active, totp_enabled, totp_secret_enc, last_login_at, created_at, updated_at, bio, avatar_id FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.TotpEnabled,
		&i.TotpSecretEnc,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, is_active, totp_enabled, totp_secret_enc, last_login_at, created_at, updated_at, bio, avatar_id FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.TotpEnabled,
		&i.TotpSecretEnc,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, full_name, is_active, totp_enabled, totp_secret_enc, last_login_at, created_at, updated_at, bio, avatar_id FROM users ORDER BY created_at DESC LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.IsActive,
			&i.TotpEnabled,
			&i.TotpSecretEnc,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
			&i.AvatarID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now(), replaced_by = $1 WHERE id = $2
`

type RevokeRefreshTokenParams struct {
	ReplacedBy *uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ReplacedBy, arg.ID)
	return err
}

const setUserTOTP = `-- name: SetUserTOTP :exec
UPDATE users SET totp_enabled = $1, totp_secret_enc = $2, updated_at = now()
WHERE id = $3
`

type SetUserTOTPParams struct {
	TotpEnabled   bool
	TotpSecretEnc []byte
	ID            uuid.UUID
}

func (q *Queries) SetUserTOTP(ctx context.Context, arg SetUserTOTPParams) error {
	_, err := q.db.Exec(ctx, setUserTOTP, arg.TotpEnabled, arg.TotpSecretEnc, arg.ID)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1, updated_at = now() WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           uuid.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET full_name = $1, is_active = $2, updated_at = now()
WHERE id = $3 RETURNING id, email, password_hash, full_name, is_active, totp_enabled, totp_secret_enc, last_login_at, created_at, updated_at, bio, avatar_id
`

type UpdateUserProfileParams struct {
	FullName string
	IsActive bool
	ID       uuid.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.FullName, arg.IsActive, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.TotpEnabled,
		&i.TotpSecretEnc,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarID,
	)
	return i, err
}

const updateUserSelfProfile = `-- name: UpdateUserSelfProfile :one
UPDATE users SET full_name = $1, bio = $2, avatar_id = $3, updated_at = now()
WHERE id = $4 RETURNING id, email, password_hash, full_name, is_active, totp_enabled, totp_secret_enc, last_login_at, created_at, updated_at, bio, avatar_id
`

type UpdateUserSelfProfileParams struct {
	FullName string
	Bio      string
	AvatarID *uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) UpdateUserSelfProfile(ctx context.Context, arg UpdateUserSelfProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSelfProfile,
		arg.FullName,
		arg.Bio,
		arg.AvatarID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.TotpEnabled,
		&i.TotpSecretEnc,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.AvatarID,
	)
	return i, err
}
