// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webhooks_audit_usage.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const aggregateUsageForDay = `-- name: AggregateUsageForDay :many
SELECT
    project_id,
    channel,
    count(*) FILTER (WHERE status IN ('queued', 'processing'))::bigint AS queued,
    count(*) FILTER (WHERE status = 'sent')::bigint                    AS sent,
    count(*) FILTER (WHERE status = 'delivered')::bigint               AS delivered,
    count(*) FILTER (WHERE status = 'failed')::bigint                  AS failed,
    coalesce(sum(cost_micros), 0)::bigint                              AS cost_micros,
    coalesce(max(currency), 'TMT')::text                               AS currency
FROM messages
WHERE created_at >= $1 AND created_at < $2 AND NOT is_test
GROUP BY project_id, channel
`

type AggregateUsageForDayParams struct {
	DayStart time.Time
	DayEnd   time.Time
}

type AggregateUsageForDayRow struct {
	ProjectID  uuid.UUID
	Channel    Channel
	Queued     int64
	Sent       int64
	Delivered  int64
	Failed     int64
	CostMicros int64
	Currency   string
}

func (q *Queries) AggregateUsageForDay(ctx context.Context, arg AggregateUsageForDayParams) ([]AggregateUsageForDayRow, error) {
	rows, err := q.db.Query(ctx, aggregateUsageForDay, arg.DayStart, arg.DayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateUsageForDayRow{}
	for rows.Next() {
		var i AggregateUsageForDayRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Channel,
			&i.Queued,
			&i.Sent,
			&i.Delivered,
			&i.Failed,
			&i.CostMicros,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (project_id, user_id, action, entity_type, entity_id, changes, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, user_id, action, entity_type, entity_id, changes, ip, user_agent, created_at
`

type CreateAuditLogParams struct {
	ProjectID  *uuid.UUID
	UserID     *uuid.UUID
	Action     string
	EntityType string
	EntityID   string
	Changes    json.RawMessage
	Ip         string
	UserAgent  string
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ProjectID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.Ip,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Changes,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (project_id, message_id, batch_id, event, url, payload, signature, next_retry_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
RETURNING id, project_id, message_id, batch_id, event, url, payload, signature, response_code, response_body, attempts, next_retry_at, delivered_at, created_at
`

type CreateWebhookDeliveryParams struct {
	ProjectID uuid.UUID
	MessageID *uuid.UUID
	BatchID   *uuid.UUID
	Event     string
	Url       string
	Payload   json.RawMessage
	Signature string
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.ProjectID,
		arg.MessageID,
		arg.BatchID,
		arg.Event,
		arg.Url,
		arg.Payload,
		arg.Signature,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MessageID,
		&i.BatchID,
		&i.Event,
		&i.Url,
		&i.Payload,
		&i.Signature,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.Attempts,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectWebhook = `-- name: GetProjectWebhook :one
SELECT id, webhook_url, webhook_secret_enc FROM projects WHERE id = $1
`

type GetProjectWebhookRow struct {
	ID               uuid.UUID
	WebhookUrl       string
	WebhookSecretEnc []byte
}

func (q *Queries) GetProjectWebhook(ctx context.Context, id uuid.UUID) (GetProjectWebhookRow, error) {
	row := q.db.QueryRow(ctx, getProjectWebhook, id)
	var i GetProjectWebhookRow
	err := row.Scan(&i.ID, &i.WebhookUrl, &i.WebhookSecretEnc)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, project_id, message_id, batch_id, event, url, payload, signature, response_code, response_body, attempts, next_retry_at, delivered_at, created_at FROM webhook_deliveries WHERE id = $1 AND project_id = $2
`

type GetWebhookDeliveryParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetWebhookDelivery(ctx context.Context, arg GetWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, arg.ID, arg.ProjectID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MessageID,
		&i.BatchID,
		&i.Event,
		&i.Url,
		&i.Payload,
		&i.Signature,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.Attempts,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookDeliveryByID = `-- name: GetWebhookDeliveryByID :one
SELECT id, project_id, message_id, batch_id, event, url, payload, signature, response_code, response_body, attempts, next_retry_at, delivered_at, created_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDeliveryByID(ctx context.Context, id uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryByID, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MessageID,
		&i.BatchID,
		&i.Event,
		&i.Url,
		&i.Payload,
		&i.Signature,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.Attempts,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, project_id, user_id, action, entity_type, entity_id, changes, ip, user_agent, created_at FROM audit_logs
WHERE ($1::uuid IS NULL OR project_id = $1::uuid)
ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type ListAuditLogsParams struct {
	ProjectID *uuid.UUID
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.ProjectID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageDaily = `-- name: ListUsageDaily :many
SELECT project_id, day, channel, queued, sent, delivered, failed, cost_micros, currency FROM usage_daily
WHERE project_id = $1 AND day >= $2 AND day <= $3
ORDER BY day, channel
`

type ListUsageDailyParams struct {
	ProjectID uuid.UUID
	FromDay   time.Time
	ToDay     time.Time
}

func (q *Queries) ListUsageDaily(ctx context.Context, arg ListUsageDailyParams) ([]UsageDaily, error) {
	rows, err := q.db.Query(ctx, listUsageDaily, arg.ProjectID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageDaily{}
	for rows.Next() {
		var i UsageDaily
		if err := rows.Scan(
			&i.ProjectID,
			&i.Day,
			&i.Channel,
			&i.Queued,
			&i.Sent,
			&i.Delivered,
			&i.Failed,
			&i.CostMicros,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, project_id, message_id, batch_id, event, url, payload, signature, response_code, response_body, attempts, next_retry_at, delivered_at, created_at FROM webhook_deliveries WHERE project_id = $1
ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type ListWebhookDeliveriesParams struct {
	ProjectID uuid.UUID
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.ProjectID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MessageID,
			&i.BatchID,
			&i.Event,
			&i.Url,
			&i.Payload,
			&i.Signature,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.Attempts,
			&i.NextRetryAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWebhookAttempt = `-- name: RecordWebhookAttempt :exec
UPDATE webhook_deliveries SET
    attempts      = attempts + 1,
    response_code = $1,
    response_body = $2,
    next_retry_at = $3,
    delivered_at  = $4
WHERE id = $5
`

type RecordWebhookAttemptParams struct {
	ResponseCode *int32
	ResponseBody string
	NextRetryAt  *time.Time
	DeliveredAt  *time.Time
	ID           uuid.UUID
}

func (q *Queries) RecordWebhookAttempt(ctx context.Context, arg RecordWebhookAttemptParams) error {
	_, err := q.db.Exec(ctx, recordWebhookAttempt,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.NextRetryAt,
		arg.DeliveredAt,
		arg.ID,
	)
	return err
}

const resetWebhookDelivery = `-- name: ResetWebhookDelivery :one
UPDATE webhook_deliveries SET attempts = 0, next_retry_at = now(), delivered_at = NULL
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, message_id, batch_id, event, url, payload, signature, response_code, response_body, attempts, next_retry_at, delivered_at, created_at
`

type ResetWebhookDeliveryParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) ResetWebhookDelivery(ctx context.Context, arg ResetWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, resetWebhookDelivery, arg.ID, arg.ProjectID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MessageID,
		&i.BatchID,
		&i.Event,
		&i.Url,
		&i.Payload,
		&i.Signature,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.Attempts,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUsageDaily = `-- name: UpsertUsageDaily :exec
INSERT INTO usage_daily (project_id, day, channel, queued, sent, delivered, failed, cost_micros, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (project_id, day, channel) DO UPDATE SET
    queued      = EXCLUDED.queued,
    sent        = EXCLUDED.sent,
    delivered   = EXCLUDED.delivered,
    failed      = EXCLUDED.failed,
    cost_micros = EXCLUDED.cost_micros,
    currency    = EXCLUDED.currency
`

type UpsertUsageDailyParams struct {
	ProjectID  uuid.UUID
	Day        time.Time
	Channel    Channel
	Queued     int64
	Sent       int64
	Delivered  int64
	Failed     int64
	CostMicros int64
	Currency   string
}

func (q *Queries) UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) error {
	_, err := q.db.Exec(ctx, upsertUsageDaily,
		arg.ProjectID,
		arg.Day,
		arg.Channel,
		arg.Queued,
		arg.Sent,
		arg.Delivered,
		arg.Failed,
		arg.CostMicros,
		arg.Currency,
	)
	return err
}
